use super::ProofApplicationSlotCeilings;

pub(super) const RELATION_PLAN_SCHEMA_IDENTIFIER: u16 = 0x2204;
pub(super) const RELATION_PLAN_VARIANT_SCHEMA_IDENTIFIER: u16 = 0x2205;
pub(super) const RELATION_COLUMN_SCHEMA_IDENTIFIER: u16 = 0x2206;
pub(super) const PROOF_CREATED_TREE_SCHEMA_IDENTIFIER: u16 = 0x2207;
pub(super) const BOUND_PUBLIC_TREE_SCHEMA_IDENTIFIER: u16 = 0x2208;
pub(super) const RELATION_CONSTRAINT_SCHEMA_IDENTIFIER: u16 = 0x2209;
pub(super) const RELATION_OPENING_POINT_SCHEMA_IDENTIFIER: u16 = 0x220a;
pub(super) const RELATION_OPENING_CLAIM_SCHEMA_IDENTIFIER: u16 = 0x220b;
pub(super) const RELATION_MASK_SCHEMA_IDENTIFIER: u16 = 0x220c;
pub(super) const SIGNED_INTEGER_SCHEMA_IDENTIFIER: u16 = 0x220d;
pub(super) const SUITE_MODULUS_REFERENCE_SCHEMA_IDENTIFIER: u16 = 0x220e;
pub(super) const RELATION_PUBLIC_SAMPLER_SCHEMA_IDENTIFIER: u16 = 0x220f;
pub(super) const BASE_FIELD_CONSTANT_SCHEMA_IDENTIFIER: u16 = 0x2210;
pub(super) const EVALUATION_VARIABLE_SCHEMA_IDENTIFIER: u16 = 0x2211;
pub(super) const COLUMN_VALUE_SCHEMA_IDENTIFIER: u16 = 0x2212;
pub(super) const TRANSCRIPT_CHALLENGE_SCHEMA_IDENTIFIER: u16 = 0x2213;
pub(super) const ADDITION_SCHEMA_IDENTIFIER: u16 = 0x2214;
pub(super) const MULTIPLICATION_SCHEMA_IDENTIFIER: u16 = 0x2215;
pub(super) const NEGATION_SCHEMA_IDENTIFIER: u16 = 0x2216;
pub(super) const NONNEGATIVE_POWER_SCHEMA_IDENTIFIER: u16 = 0x2217;
#[cfg(test)]
pub(super) const RADIX_CONVOLUTION_COEFFICIENT_SCHEMA_IDENTIFIER: u16 = 0x2219;
pub(super) const TRACE_DOMAIN_EXCEPT_ROOTS_SCHEMA_IDENTIFIER: u16 = 0x221a;
pub(super) const NON_NATIVE_MODULUS_CONSTANT_SCHEMA_IDENTIFIER: u16 = 0x221b;
pub(super) const APPLICATION_STATEMENT_SOURCE_SCHEMA_IDENTIFIER: u16 = 0x2220;
pub(super) const PROTOCOL_SOURCE_SCHEMA_IDENTIFIER: u16 = 0x2221;
pub(super) const SELECTOR_PATH_STEP_SCHEMA_IDENTIFIER: u16 = 0x2225;
pub(super) const VALUE_LAYOUT_SCHEMA_IDENTIFIER: u16 = 0x2226;
pub(super) const VERIFIER_SEQUENCE_COLUMN_ORIGIN_SCHEMA_IDENTIFIER: u16 = 0x2227;
pub(super) const BOUND_TREE_COLUMN_ORIGIN_SCHEMA_IDENTIFIER: u16 = 0x2228;
pub(super) const PROVER_COLUMN_ORIGIN_SCHEMA_IDENTIFIER: u16 = 0x2229;
pub(super) const SEMANTIC_CELL_SCHEMA_IDENTIFIER: u16 = 0x2234;
pub(super) const TRINARY_BOUND_CERTIFICATE_SCHEMA_IDENTIFIER: u16 = 0x2235;
pub(super) const BINARY_BOUND_CERTIFICATE_SCHEMA_IDENTIFIER: u16 = 0x2236;
pub(super) const UNSIGNED_RECOMPOSITION_BOUND_CERTIFICATE_SCHEMA_IDENTIFIER: u16 = 0x2237;
pub(super) const SHIFTED_RECOMPOSITION_BOUND_CERTIFICATE_SCHEMA_IDENTIFIER: u16 = 0x2238;
#[cfg(test)]
pub(super) const RADIX_COLUMN_DIGITS_SCHEMA_IDENTIFIER: u16 = 0x2239;
#[cfg(test)]
pub(super) const RADIX_CONSTANT_DIGITS_SCHEMA_IDENTIFIER: u16 = 0x223a;
#[cfg(test)]
pub(super) const RADIX_SCALAR_COLUMN_SCHEMA_IDENTIFIER: u16 = 0x223b;
#[cfg(test)]
pub(super) const RADIX_PRODUCT_TERM_SCHEMA_IDENTIFIER: u16 = 0x223c;
#[cfg(test)]
pub(super) const RADIX_CONVOLUTION_SCHEMA_IDENTIFIER: u16 = 0x223d;
pub(super) const CANONICAL_MODULUS_RECOMPOSITION_BOUND_CERTIFICATE_SCHEMA_IDENTIFIER: u16 = 0x2240;
pub(super) const INJECTIVE_INTEGER_FACTOR_PROGRAM_SCHEMA_IDENTIFIER: u16 = 0x2241;
pub(super) const FINITE_INTEGER_SET_BOUND_CERTIFICATE_SCHEMA_IDENTIFIER: u16 = 0x2242;
pub(super) const INTEGER_LIFT_LINEAR_TERM_SCHEMA_IDENTIFIER: u16 = 0x2243;
pub(super) const INTEGER_LIFT_CONVOLUTION_PRODUCT_SCHEMA_IDENTIFIER: u16 = 0x2244;
pub(super) const INTEGER_LIFT_COMPONENT_SCHEMA_IDENTIFIER: u16 = 0x2245;
pub(super) const INTEGER_LIFT_BATCH_SCHEMA_IDENTIFIER: u16 = 0x2246;
pub(super) const INTEGER_LIFT_CONSTANT_COEFFICIENT_SCHEMA_IDENTIFIER: u16 = 0x2247;
pub(super) const INTEGER_LIFT_MODULUS_COEFFICIENT_SCHEMA_IDENTIFIER: u16 = 0x2248;
pub(super) const INTEGER_LIFT_FULL_RING_NEGACYCLIC_PRODUCT_SCHEMA_IDENTIFIER: u16 = 0x2249;
pub(super) const INTEGER_LIFT_REVERSED_COLUMN_BINDING_SCHEMA_IDENTIFIER: u16 = 0x224a;
pub(super) const COEFFICIENT_LOCAL_RESIDUAL_SCHEMA_IDENTIFIER: u16 = 0x224b;
pub(super) const COEFFICIENT_LOCAL_IDENTITY_BATCH_SCHEMA_IDENTIFIER: u16 = 0x224c;
pub(super) const NEGACYCLIC_AUTOMORPHISM_MAPPING_SOURCE_SCHEMA_IDENTIFIER: u16 = 0x224d;
pub(super) const INTEGER_LIFT_NEGACYCLIC_AUTOMORPHISM_PERMUTATION_SCHEMA_IDENTIFIER: u16 = 0x224e;
pub(super) const RADIX_DECOMPOSED_VERIFIER_SOURCE_SCHEMA_IDENTIFIER: u16 = 0x224f;
pub(super) const INTEGER_LIFT_MODULUS_RADIX_DIGIT_COEFFICIENT_SCHEMA_IDENTIFIER: u16 = 0x2250;
pub(super) const DIRECT_BALLOT_PAIR_CHARACTER_ENCODER_PROFILE_SOURCE_SCHEMA_IDENTIFIER: u16 =
    0x2251;
pub(super) const CONSTANT_COLUMN_VERIFIER_SEQUENCE_PRODUCT_SUM_SCHEMA_IDENTIFIER: u16 = 0x2252;
pub(super) const CONSTANT_COLUMN_VERIFIER_SEQUENCE_PRODUCT_TERM_SCHEMA_IDENTIFIER: u16 = 0x2253;
pub(super) const SCHEMA_VERSION: u16 = 1;
pub(super) const RELATION_PLAN_HASH_DOMAIN: &str = "sealed-lattice/proof/relation-plan/v1";
pub(super) const RELATION_PLAN_VARIANT_HASH_DOMAIN: &str =
    "sealed-lattice/proof/relation-plan-variant/v1";

pub(super) const PUBLIC_ONLY_FAMILIES: [u16; 3] =
    ProofApplicationSlotCeilings::PUBLIC_ONLY_FAMILY_SCHEMA_IDENTIFIERS;
pub(super) const SECRET_BEARING_FAMILIES: [u16; 9] =
    ProofApplicationSlotCeilings::SECRET_BEARING_FAMILY_SCHEMA_IDENTIFIERS;
pub(super) const MAXIMUM_EXHAUSTIVE_ZEROIFIER_COSET_CHECK_DOMAIN_SIZE: u64 = 1 << 16;
