[package]
name = "setup-aggregate"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["rlib"]

[features]
default = ["bridge"]
bridge = []

[dependencies]
num-bigint = "=0.5.1"

opened-contribution = { path = "../opened-contribution", default-features = false }
parallel-work = { path = "../parallel-work" }
registration-credentials = { path = "../registration-credentials", default-features = false }
supported-profile = { path = "../supported-profile" }
