[package]
name = "protocol-foundations"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
fips204 = { workspace = true, features = ["ml-dsa-65"] }
parallel-work = { path = "../parallel-work" }
sha3.workspace = true
unicode-normalization = "=0.1.25"
zeroize.workspace = true
supported-profile = { path = "../supported-profile" }
