[package]
name = "ballot-proof"
version = "0.0.0"
edition = "2024"
publish = false
autobins = false


[lib]
crate-type = ["rlib", "cdylib"]

[features]
default = ["bridge"]
bridge = ["ballot-encryption/bridge", "setup-aggregate/bridge"]

[dependencies]
proof-lookup-table = { path = "../proof-lookup-table" }
ballot-encryption = { path = "../ballot-encryption", default-features = false }
setup-aggregate = { path = "../setup-aggregate", default-features = false }
registration-credentials = { path = "../registration-credentials", default-features = false }
setup-stream-kernel = { path = "../setup-stream-kernel", default-features = false }
num-bigint = "=0.5.1"
sha3 = "=0.10.9"
sha2 = "=0.10.9"
setup-witness = { path = "../setup-witness" }
stateful-sha3 = { package = "sha3", version = "=0.12.0", default-features = false, features = ["zeroize"] }
zeroize = "=1.8.2"
fips204 = { version = "=0.4.6", default-features = false, features = ["ml-dsa-65"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
getrandom = "=0.3.3"
