[package]
name = "contribution-prover"
version = "0.0.0"
edition = "2024"
publish = false
autobins = false


[lib]
crate-type = ["rlib"]

[dependencies]
parallel-work = { path = "../parallel-work" }
registration-credentials = { path = "../registration-credentials" }
setup-witness = { path = "../setup-witness" }
supported-profile = { path = "../supported-profile" }
word-proof = { path = "../word-proof" }
num-bigint = "=0.5.1"
num-traits = "=0.2.19"
sha3 = "=0.10.9"
zeroize = "=1.8.2"
