[workspace]
members = [
    "crates/sealed-lattice-kernel",
    "tools/process-memory-guard",
]
exclude = [
    "third-party/plonky3-p3-util-f07da1c479c519040cca27924184c2730315e202",
]
resolver = "3"

[patch."https://github.com/Plonky3/Plonky3.git"]
p3-util = { path = "third-party/plonky3-p3-util-f07da1c479c519040cca27924184c2730315e202" }

[profile.test]
opt-level = 3
overflow-checks = true

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = 3
panic = "abort"
