[package]
name = "setup-witness"
version = "0.0.0"
edition = "2024"
publish = false
autobins = false


[lib]
crate-type = ["rlib"]

[dependencies]
aes-gcm = { version = "=0.10.3", default-features = false, features = ["aes", "alloc", "zeroize"], optional = true }
aes = { version = "=0.8.4", features = ["zeroize"], optional = true }
num-bigint = "=0.5.1"
num-traits = "=0.2.19"
sha3 = "=0.10.9"
zeroize = "=1.8.2"
linked-release-proof = { path = "../linked-release-proof", default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
getrandom = "=0.3.3"

[features]
custody = ["dep:aes-gcm", "dep:aes"]
