[package]
name = "sealed-lattice-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "=0.4.13"
sealed-lattice-kernel = { path = "../crates/sealed-lattice-kernel" }

[workspace]
members = ["."]

[[bin]]
name = "foundation-schema-object"
path = "fuzz_targets/foundation-schema-object.rs"
test = false
doc = false
bench = false
