[package]
name = "ballot-encryption"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
zeroize.workspace = true

num-bigint.workspace = true
parallel-work = { path = "../parallel-work" }
setup-aggregate = { path = "../setup-aggregate" }
setup-witness = { path = "../setup-witness" }
protocol-foundations = { path = "../protocol-foundations" }
supported-profile = { path = "../supported-profile" }

[dev-dependencies]
num-traits.workspace = true
