[package]
name = "public-operator-screen"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
num-bigint = "=0.5.1"
opening-share-proof = { path = "../opening-share-proof" }
parallel-work = { path = "../parallel-work" }
seed-sharing-proof = { path = "../seed-sharing-proof" }
setup-stream-kernel = { path = "../setup-stream-kernel" }
supported-profile = { path = "../supported-profile" }
word-proof = { path = "../word-proof" }

[[bin]]
name = "screen-public-operator"
path = "src/bin/screen-public-operator.rs"
