[package]
name = "registration-credentials"
version = "0.0.0"
edition = "2024"
publish = false
autobins = false

[dependencies]
aes-gcm = { version = "=0.10.3", default-features = false, features = ["aes", "alloc", "zeroize"] }
aes = { version = "=0.8.4", features = ["zeroize"] }
fips204 = { version = "=0.4.6", default-features = false, features = ["ml-dsa-65"] }
parallel-work = { path = "../parallel-work" }
sha3 = "=0.10.9"
unicode-normalization = "=0.1.25"
zeroize = "=1.8.2"
registration-proof = { path = "../registration-proof" }
linked-release-proof = { path = "../linked-release-proof" }
supported-profile = { path = "../supported-profile" }
