[package]
name = "word-verifier"
version = "0.0.0"
edition = "2024"
publish = false
autobins = false


[lib]
crate-type = ["rlib"]

[dependencies]
parallel-work = { path = "../parallel-work" }
proof-lookup-table = { path = "../proof-lookup-table" }
sha3 = "=0.10.9"
setup-stream-kernel = { path = "../setup-stream-kernel" }
supported-profile = { path = "../supported-profile" }

[dev-dependencies]
word-proof = { path = "../word-proof" }
