/** Hex digest string used for canonical protocol objects and policies. */
export type ProtocolDigest = string;

/** Reserved protocol digest namespaces accepted by the transcript-core registry. */
export const protocolDigestNamespaceValues = [
    'BoardEntryDigest',
    'BoardRootDigest',
    'BoardPolicyDigest',
    'PollSpecDigest',
    'PublicKeyDigest',
    'RegistrationEntryDigest',
    'ReceiverKeyRegistrationDigest',
    'TrusteeSetupEntryDigest',
    'ElectionManifestDigest',
    'RosterDigest',
    'RosterExternalAcceptanceDigest',
    'BoardHeadDigest',
    'RecoveryEpochUpdateDigest',
    'ActionContextDigest',
    'BallotPackageDigest',
    'BallotSetDigest',
    'CastReceiptDigest',
    'CloseRecordDigest',
    'WitnessCheckpointDigest',
    'ConflictingHeadEvidenceDigest',
    'WitnessEquivocationEvidenceDigest',
    'InclusionProofDigest',
    'FirstValidOrderDigest',
    'DuplicateBallotPolicyDigest',
    'FirstValidPolicyDigest',
    'TargetFinalityPolicyDigest',
    'WitnessPolicyDigest',
    'RecoveryPolicyDigest',
    'SignedRootDigest',
    'ProtocolSignatureEnvelopeDigest',
    'ProviderBuildDigest',
    'MlDsaFixtureSeedDigest',
    'ThresholdProfileDigest',
    'HEParamDigest',
    'BGVProfileDigest',
    'RustBgvBackendProfileDigest',
    'EncryptedAggregateBridgeDigest',
    'EncryptedAggregateInputRoot',
    'EncryptedAggregateShareCiphertextRoot',
    'EncryptedAggregateReconstructionDigest',
    'BridgeWitnessPrivacyProfileDigest',
    'ScoreBitDerivationCircuitDigest',
    'ComparisonInputDerivationCircuitDigest',
    'EncryptedComparisonInputDigest',
    'CiphertextRoot',
    'PlaintextRoot',
    'PlaintextTallyDigest',
    'PlaintextTopKOracleDigest',
    'InterpolationCoefficientReportDigest',
    'WorstCaseInterpolationCoefficientReportDigest',
    'SparseTopKTargetDigest',
    'BGVPassiveSetupPackageDigest',
    'ParticipantBgvSetupRecordDigest',
    'PublicKeyShareRoot',
    'BGVPublicKeyRoot',
    'CollectivePublicKeyRoot',
    'RelinearizationKeyRoot',
    'RotationKeyRoot',
    'KeySwitchKeyRoot',
    'KeySwitchDecompositionDigest',
    'EvalKeyRoot',
    'EvaluationKeySizeProfileDigest',
    'CollectiveSecretDistributionCertificateDigest',
    'ErrorDistributionCertificateDigest',
    'BGVSetupParameterCertificateDigest',
    'BGVDevelopmentEncryptionFixtureDigest',
    'TopKCircuitDigest',
    'RotSetDigest',
    'TargetLayoutDigest',
    'PublicSlotMaskDigest',
    'AggregateDerivationComponentDigest',
    'AggregateContributionDigest',
    'AggregateReadyRecordDigest',
    'AggregateSelectionPolicyDigest',
    'PostVotingClosedContextDigest',
    'EvaluationContextDigest',
    'TopKEvaluationRecordDigest',
    'TargetProposalDigest',
    'TargetFinalityCheckpointDigest',
    'TargetFinalityRecordDigest',
    'EvaluationProofRecordDigest',
    'EvaluationProofProfileDigest',
    'TargetAcceptedRecordDigest',
    'TargetPreimageDigest',
    'TargetContextDigest',
    'LocalReplayRecordDigest',
    'LocalReplayDiagnosticDigest',
    'TopKDecryptionShareDigest',
    'VerifiedTopKResultDigest',
    'CPADProfileDigest',
    'CPADProfileVerificationDigest',
    'ThresholdDecryptionProfileDigest',
    'KllpsTargetDecryptionProfileDigest',
    'BridgeProofRecordDigest',
    'CanonicalCiphertextConventionDigest',
    'BGVBatchEncoderDigest',
    'BGVBatchEncoderLayoutBindingDigest',
    'EvaluationNoiseProfileDigest',
    'HEEvaluationNoiseCertDigest',
    'AllowedEvaluatorOpsDigest',
    'EvaluatorProgramDigest',
    'BridgeLayoutDigest',
    'AggregateShareCommitmentDigest',
    'ShareCommitmentDigest',
    'BallotPolynomialSetDigest',
    'TestReceiverShareOpeningPayloadDigest',
    'ThresholdShareVerificationKeyRoot',
    'ThresholdShareVerificationKeyDigest',
    'TrusteeThresholdVerificationKeyDigest',
    'TargetDecryptionPreparationRecordDigest',
    'TargetDecryptionCiphertextDigest',
    'ShareReplayEvidenceDigest',
    'ShareReplayRefusalDigest',
    'TargetBasisDigest',
    'MobileProfileCertDigest',
    'BridgeBenchmarkReportPolicyDigest',
    'BridgeBatchingCertDigest',
    'AggregateBridgeProverCertDigest',
    'EncryptedEnvelopeRoot',
    'ReceiverEncryptionProfileDigest',
    'ShareCommitmentProfileDigest',
    'BallotProofProfileDigest',
    'BallotPrivacyRosterProfileEvidenceDigest',
    'ScoreMembershipProfileDigest',
    'BallotScoreEncodingProfileDigest',
    'BallotShareLayoutProfileDigest',
    'AggregateInputEncodingProfileDigest',
    'EncodedShareVectorLayoutDigest',
    'EncodedAggregateLayoutDigest',
    'TopKEvaluatorInputLayoutDigest',
    'ShareCommitmentMessageBoundCertDigest',
    'ReceiverPayloadDigest',
    'ReceiverPayloadCiphertextRoot',
    'ReceiverKeyProofRoot',
    'BallotProofStatementDigest',
    'BallotProofRecordDigest',
    'ProofBytesDigest',
    'ChallengeDomainDigest',
] as const;

export type ProtocolDigestNamespace =
    (typeof protocolDigestNamespaceValues)[number];

/** Semantic Hash names for document-facing APIs that still resolve to v1 namespaces. */
export const protocolHashSemanticNameValues = [
    'ManifestHash',
    'RosterHash',
    'LocalRosterAcceptanceHash',
    'TargetProposalHash',
    'EvaluationContextHash',
    'TopKEvaluationRecordHash',
    'EvaluationProofRecordHash',
    'TargetAcceptedRecordHash',
    'TargetContextHash',
    'TargetPreimageHash',
    'TargetCiphertextHash',
    'EncryptedAggregateInputRootHash',
    'KllpsTargetDecryptionProfileHash',
    'LocalReplayRecordHash',
    'LocalReplayDiagnosticHash',
] as const;

export type ProtocolHashSemanticName =
    (typeof protocolHashSemanticNameValues)[number];

export type ProtocolHash = ProtocolDigest;

export const protocolDigestNamespaceByHashAlias = {
    ManifestHash: 'ElectionManifestDigest',
    RosterHash: 'RosterDigest',
    LocalRosterAcceptanceHash: 'RosterExternalAcceptanceDigest',
    TargetProposalHash: 'TargetProposalDigest',
    EvaluationContextHash: 'EvaluationContextDigest',
    TopKEvaluationRecordHash: 'TopKEvaluationRecordDigest',
    EvaluationProofRecordHash: 'EvaluationProofRecordDigest',
    TargetAcceptedRecordHash: 'TargetAcceptedRecordDigest',
    TargetContextHash: 'TargetContextDigest',
    TargetPreimageHash: 'TargetPreimageDigest',
    TargetCiphertextHash: 'CiphertextRoot',
    EncryptedAggregateInputRootHash: 'EncryptedAggregateInputRoot',
    KllpsTargetDecryptionProfileHash: 'KllpsTargetDecryptionProfileDigest',
    LocalReplayRecordHash: 'LocalReplayRecordDigest',
    LocalReplayDiagnosticHash: 'LocalReplayDiagnosticDigest',
} as const satisfies Record<ProtocolHashSemanticName, ProtocolDigestNamespace>;

export const protocolHashAliasByDigestNamespace = {
    ElectionManifestDigest: 'ManifestHash',
    RosterDigest: 'RosterHash',
    RosterExternalAcceptanceDigest: 'LocalRosterAcceptanceHash',
    TargetProposalDigest: 'TargetProposalHash',
    EvaluationContextDigest: 'EvaluationContextHash',
    TopKEvaluationRecordDigest: 'TopKEvaluationRecordHash',
    EvaluationProofRecordDigest: 'EvaluationProofRecordHash',
    TargetAcceptedRecordDigest: 'TargetAcceptedRecordHash',
    TargetContextDigest: 'TargetContextHash',
    TargetPreimageDigest: 'TargetPreimageHash',
    CiphertextRoot: 'TargetCiphertextHash',
    EncryptedAggregateInputRoot: 'EncryptedAggregateInputRootHash',
    KllpsTargetDecryptionProfileDigest: 'KllpsTargetDecryptionProfileHash',
    LocalReplayRecordDigest: 'LocalReplayRecordHash',
    LocalReplayDiagnosticDigest: 'LocalReplayDiagnosticHash',
} as const satisfies Partial<
    Record<ProtocolDigestNamespace, ProtocolHashSemanticName>
>;
