[package]
name = "statement-stream"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
parallel-work = { path = "../parallel-work" }
supported-profile = { path = "../supported-profile" }

[dev-dependencies]
num-bigint.workspace = true
num-traits.workspace = true
