[package]
name = "registration-verifier"
version = "0.0.0"
edition = "2024"
publish = false
autobins = false


[dependencies]
parallel-work = { path = "../parallel-work" }
proof-lookup-table = { path = "../proof-lookup-table" }
registration-proof = { path = "../registration-proof" }
setup-stream-kernel = { path = "../setup-stream-kernel" }
sha3 = "=0.10.9"
supported-profile = { path = "../supported-profile" }
