[package]
name = "opened-contribution"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["rlib"]

[dependencies]
registration-credentials = { path = "../registration-credentials" }
parallel-work = { path = "../parallel-work" }
setup-witness = { path = "../setup-witness" }
word-verifier = { path = "../word-verifier" }
