[package]
name = "setup-stream-kernel"
version = "0.0.0"
edition = "2024"
publish = false
autobins = false


[lib]
crate-type = ["rlib"]


[dependencies]
parallel-work = { path = "../parallel-work" }
supported-profile = { path = "../supported-profile" }

[dev-dependencies]
num-bigint = "=0.5.1"
num-traits = "=0.2.19"
