import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import {
    exactRankingModelConstants,
    compilePackedRankingEvaluationGraph,
    verifyExactRankingModel,
} from '#tests/exact-ranking-model.js';
import { compileSupportedThresholdCompletionProfiles } from '#tests/threshold-completion-model.js';

const formatCount = (value: bigint | number): string =>
    `\`${value.toLocaleString('en-US')}\``;

const table = (
    header: readonly string[],
    rows: readonly (readonly string[])[],
): string =>
    [
        `| ${header.join(' | ')} |`,
        `| ${header.map(() => '---').join(' | ')} |`,
        ...rows.map((row) => `| ${row.join(' | ')} |`),
    ].join('\n');

export const renderDocumentationCensus = (): string => {
    const thresholdProfiles = compileSupportedThresholdCompletionProfiles();
    const rankingCensus = verifyExactRankingModel();
    const completionGraph = compilePackedRankingEvaluationGraph(10, 10, 10);
    const maximumGraph = compilePackedRankingEvaluationGraph(20, 20, 20);

    return `${[
        '# Documentation census',
        '',
        'Generated by `pnpm run docs:census` from the independent TypeScript models under `tests/`. Do not edit by hand. These are model-derived development values, not a protocol theorem, concrete FHE parameter approval, browser measurement, or supported-phone qualification.',
        '',
        '## Threshold completion census',
        '',
        'For each supported roster, the model uses `f = floor((n - 1) / 3)`, inventory-certificate threshold `q = n - f`, and result-release threshold `d = f + 1`. Every named set is counted; isomorphic joint cases are checked with exact multiplicity, and profiles through twelve participants are also brute-force cross-checked over the underlying bit masks.',
        '',
        table(
            [
                'Participants',
                'Maximum corrupt',
                'Inventory certificate',
                'Result release',
                'Guaranteed honest responders',
                'Minimum certificate intersection',
                'Mandatory release positions',
                'Corruption/disappearance/refusal cases',
                'Ordered certificate pairs',
                'Brute-force cross-check',
            ],
            thresholdProfiles.map((profile) => [
                String(profile.participantCount),
                String(profile.maximumCorruptParticipantCount),
                String(profile.inventoryCertificateThreshold),
                String(profile.resultReleaseThreshold),
                String(profile.guaranteedHonestResponderCount),
                String(profile.minimumCertificateIntersection),
                String(profile.mandatoryReleaseParticipantCount),
                formatCount(profile.corruptionDisappearanceRefusalCaseCount),
                formatCount(profile.orderedCertificatePairCount),
                profile.bruteForceCrossChecked ? 'yes' : 'class-counted',
            ]),
        ),
        '',
        '## Exact ranking arithmetic census',
        '',
        table(
            ['Property', 'Value'],
            [
                [
                    'Plaintext modulus used by the arithmetic experiment',
                    formatCount(exactRankingModelConstants.plaintextModulus),
                ],
                [
                    'Maximum total difference magnitude',
                    formatCount(exactRankingModelConstants.maximumDifference),
                ],
                [
                    'Comparison interpolation points',
                    formatCount(rankingCensus.exhaustiveComparisonPointCount),
                ],
                [
                    'Comparison polynomial degree',
                    formatCount(rankingCensus.comparisonPolynomialDegree),
                ],
                [
                    'Nonzero comparison coefficients',
                    formatCount(
                        rankingCensus.comparisonPolynomialNonzeroCoefficientCount,
                    ),
                ],
                [
                    'Rank-equality domains checked',
                    formatCount(rankingCensus.equalityDomainCount),
                ],
                [
                    'Participant/option profiles checked',
                    formatCount(
                        rankingCensus.testedParticipantOptionProfileCount,
                    ),
                ],
                [
                    'Adversarial and deterministic score matrices checked',
                    formatCount(rankingCensus.testedMatrixCount),
                ],
                [
                    'Result-width executions checked',
                    formatCount(rankingCensus.testedTopCountExecutionCount),
                ],
            ],
        ),
        '',
        'The comparison returns one when a lower canonical option position has a nonnegative total difference. This incorporates the lower-position tie rule. Rank-equality polynomials are independently interpolated and exhaustively checked on every rank domain from two through twenty options.',
        '',
        '## Packed ranking graph census',
        '',
        'The graph uses one packed ciphertext per accepted ballot. Each cyclic shift masks the lanes for which the current option has the lower canonical position, evaluates one block-size-24 Paterson-Stockmeyer non-strict comparison, and routes both pairwise rank contributions. It then shares rank powers, performs masked slot reduction, and packs one ordered output. The ciphertext-byte projection assumes a polynomial modulus degree of 32,768, 64-bit RNS limbs, and one remaining data prime per consumed multiplicative level. It counts scheduled data ciphertexts only; evaluation keys, scratch allocations, serialization copies, proof data, and the WebAssembly runtime are additional. This is not a selected parameter set.',
        '',
        table(
            [
                'Graph property',
                'Ten participants/options',
                'Twenty participants/options',
            ],
            [
                [
                    'Multiplicative depth',
                    formatCount(completionGraph.multiplicativeDepth),
                    formatCount(maximumGraph.multiplicativeDepth),
                ],
                [
                    'Ciphertext multiplications',
                    formatCount(completionGraph.ciphertextMultiplicationCount),
                    formatCount(maximumGraph.ciphertextMultiplicationCount),
                ],
                [
                    'Relinearizations',
                    formatCount(completionGraph.relinearizationCount),
                    formatCount(maximumGraph.relinearizationCount),
                ],
                [
                    'Rotations',
                    formatCount(completionGraph.rotationCount),
                    formatCount(maximumGraph.rotationCount),
                ],
                [
                    'Ciphertext additions',
                    formatCount(completionGraph.ciphertextAdditionCount),
                    formatCount(maximumGraph.ciphertextAdditionCount),
                ],
                [
                    'Plaintext multiplications',
                    formatCount(completionGraph.plaintextMultiplicationCount),
                    formatCount(maximumGraph.plaintextMultiplicationCount),
                ],
                [
                    'Scheduled peak live ciphertexts',
                    formatCount(
                        completionGraph.scheduledPeakLiveCiphertextCount,
                    ),
                    formatCount(maximumGraph.scheduledPeakLiveCiphertextCount),
                ],
                [
                    'Projected scheduled peak ciphertext bytes',
                    formatCount(
                        completionGraph.scheduledPeakCiphertextByteLength,
                    ),
                    formatCount(maximumGraph.scheduledPeakCiphertextByteLength),
                ],
                [
                    'Materialized graph nodes',
                    formatCount(
                        completionGraph.materializedCiphertextNodeCount,
                    ),
                    formatCount(maximumGraph.materializedCiphertextNodeCount),
                ],
            ],
        ),
    ].join('\n')}\n`;
};

const normalizeCensusLine = (line: string): string =>
    line.startsWith('|')
        ? line
              .split('|')
              .map((cell) => cell.trim().replace(/^-{3,}$/u, '---'))
              .join('|')
        : line;

const normalizeCensusText = (text: string): string[] =>
    text.replace(/\r\n/g, '\n').split('\n').map(normalizeCensusLine);

export const findFirstCensusMismatch = (
    stored: string,
    rendered: string,
): number | undefined => {
    const storedLines = normalizeCensusText(stored);
    const renderedLines = normalizeCensusText(rendered);
    const length = Math.max(storedLines.length, renderedLines.length);
    for (let index = 0; index < length; index += 1) {
        if (storedLines[index] !== renderedLines[index]) return index + 1;
    }
    return undefined;
};

const usage =
    'Usage: generate-documentation-census.ts (--output <file> | --check <file> | --print)';

const main = async (): Promise<void> => {
    const rawArguments = process.argv.slice(2);
    const argumentsList =
        rawArguments[0] === '--' ? rawArguments.slice(1) : rawArguments;
    const rendered = renderDocumentationCensus();
    if (argumentsList.length === 1 && argumentsList[0] === '--print') {
        process.stdout.write(rendered);
        return;
    }
    if (argumentsList.length !== 2 || argumentsList[1] === undefined) {
        throw new Error(usage);
    }
    const targetPath = path.resolve(argumentsList[1]);
    if (argumentsList[0] === '--output') {
        await writeFile(targetPath, rendered, 'utf8');
        process.stdout.write(
            `Wrote ${String(Buffer.byteLength(rendered))} bytes to ${targetPath}\n`,
        );
        return;
    }
    if (argumentsList[0] === '--check') {
        const stored = await readFile(targetPath, 'utf8');
        const mismatch = findFirstCensusMismatch(stored, rendered);
        if (mismatch !== undefined) {
            throw new Error(
                `The stored census is stale at line ${String(mismatch)}; regenerate it with --output.`,
            );
        }
        process.stdout.write('The stored census matches the models.\n');
        return;
    }
    throw new Error(usage);
};

if (import.meta.main) await main();
