import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import {
    actionSignatureByteLength,
    actionSignatureSecretKeyByteLength,
    actionSignatureVerificationKeyByteLength,
} from '#packages/wasm/src/action-signature-runtime.js';
import { finalityTargetBodyByteLength } from '#packages/wasm/src/finality-runtime.js';
import {
    maximumFoundationCopiedBufferByteLength,
    maximumFoundationWasmMemoryByteLength,
} from '#packages/wasm/src/foundation-contract.js';
import {
    pairDecryptionKeyByteLength,
    pairEncryptionKeyByteLength,
} from '#packages/wasm/src/pair-encryption-runtime.js';
import {
    preparationContributionOpeningVectorByteLength,
    preparationPairwiseMasterVectorByteLength,
    preparationPlaintextByteLength,
} from '#packages/wasm/src/preparation-material-runtime.js';
import {
    actionSignatureCarrierByteLength,
    preparationParentBodyByteLength,
} from '#packages/wasm/src/preparation-parent-runtime.js';
import { privatePreparationBodyByteLength } from '#packages/wasm/src/private-preparation-body-runtime.js';
import { completionRosterByteLength } from '#packages/wasm/src/roster-runtime.js';
import {
    abstentionSourceBodyByteLength,
    submittedSourceBodyByteLength,
} from '#packages/wasm/src/source-runtime.js';
import {
    compileCompletionPreparationModel,
    enumerateCorruptProjectionCensuses,
} from '#tests/complete-preparation-model.js';
import { compileFullTallyResourceModel } from '#tests/full-tally-resource-model.js';
import { compileFullTallySecurityLedger } from '#tests/full-tally-security-ledger.js';
import { localRecordContextByteLength } from '#tests/local-record-context-model.js';
import {
    compileIndependentPaddedTallyModel,
    projectIndependentPaddedTallyWidth,
} from '#tests/padded-tally-transcript-model.js';

const participantCount = 10;
const maximumTopCount = 10;
const maximumCorruptParticipantCount = 3;
const emittedLabelByteLength = 40;
const dormantProjectionLabelByteLength = 192;

const formatCount = (value: number | bigint): string =>
    `\`${value.toLocaleString('en-US')}\``;

const table = (
    header: readonly string[],
    rows: readonly (readonly string[])[],
): string =>
    [
        `| ${header.join(' | ')} |`,
        `| ${header.map(() => '---').join(' | ')} |`,
        ...rows.map((row) => `| ${row.join(' | ')} |`),
    ].join('\n');

const topCounts = Array.from(
    { length: maximumTopCount },
    (_, index) => index + 1,
);

/**
 * Renders the documentation census from the independent TypeScript models.
 * The output is deterministic and carries no timestamp, so a stale copy is
 * detected by byte comparison.
 */
export const renderDocumentationCensus = (): string => {
    const perWidth = topCounts.map((topCount) => {
        const tally = compileIndependentPaddedTallyModel(topCount);
        return {
            topCount,
            tally,
            emitted: projectIndependentPaddedTallyWidth(
                tally,
                emittedLabelByteLength,
            ),
            dormant: projectIndependentPaddedTallyWidth(
                tally,
                dormantProjectionLabelByteLength,
            ),
            preparation: compileCompletionPreparationModel(tally),
            ledger: compileFullTallySecurityLedger(topCount),
            resourceAllSubmitted: compileFullTallyResourceModel(
                topCount,
                participantCount,
            ),
            resourceQuorumSubmitted: compileFullTallyResourceModel(topCount, 8),
        };
    });
    const maximum = perWidth[perWidth.length - 1];
    if (maximum === undefined) {
        throw new Error('The census requires at least one output width.');
    }
    const corruptProjection = enumerateCorruptProjectionCensuses(
        maximumCorruptParticipantCount,
    )[0];
    if (corruptProjection === undefined) {
        throw new Error('The maximum-corruption projection is absent.');
    }

    const sections: string[] = [];
    sections.push(
        [
            '# Documentation census',
            '',
            'Generated by `pnpm run docs:census` from the independent TypeScript models under `tests/`. Do not edit by hand; regenerate after any model change and verify with `--check`. Every count is derived from the completion profile of ten participants, ten options, and at most three corrupt participants. Measured run values live in run diagnostics, not here.',
        ].join('\n'),
    );

    sections.push(
        [
            '## Canonical object lengths',
            '',
            'Fixed byte lengths exported by the bridge modules and the local-record model.',
            '',
            table(
                ['Object', 'Bytes'],
                [
                    [
                        'Canonical roster',
                        formatCount(completionRosterByteLength),
                    ],
                    [
                        'ML-DSA-65 verification key',
                        formatCount(actionSignatureVerificationKeyByteLength),
                    ],
                    [
                        'ML-DSA-65 secret key',
                        formatCount(actionSignatureSecretKeyByteLength),
                    ],
                    [
                        'ML-DSA-65 signature',
                        formatCount(actionSignatureByteLength),
                    ],
                    [
                        'Action signature carrier',
                        formatCount(actionSignatureCarrierByteLength),
                    ],
                    [
                        'ML-KEM-768 encapsulation key',
                        formatCount(pairEncryptionKeyByteLength),
                    ],
                    [
                        'ML-KEM-768 decapsulation key',
                        formatCount(pairDecryptionKeyByteLength),
                    ],
                    [
                        'Preparation parent body',
                        formatCount(
                            preparationParentBodyByteLength(participantCount),
                        ),
                    ],
                    [
                        'Private preparation body',
                        formatCount(privatePreparationBodyByteLength),
                    ],
                    [
                        'Preparation plaintext',
                        formatCount(preparationPlaintextByteLength),
                    ],
                    [
                        'Contribution opening vector',
                        formatCount(
                            preparationContributionOpeningVectorByteLength,
                        ),
                    ],
                    [
                        'Directed pairwise master vector',
                        formatCount(preparationPairwiseMasterVectorByteLength),
                    ],
                    [
                        'Abstention source body',
                        formatCount(abstentionSourceBodyByteLength),
                    ],
                    [
                        'Submitted source body',
                        formatCount(submittedSourceBodyByteLength),
                    ],
                    [
                        'Finality target body',
                        formatCount(finalityTargetBodyByteLength),
                    ],
                    [
                        'Local-record context',
                        formatCount(localRecordContextByteLength),
                    ],
                    [
                        'Absolute copied-buffer bound',
                        formatCount(maximumFoundationCopiedBufferByteLength),
                    ],
                    [
                        'Absolute WebAssembly memory bound',
                        formatCount(maximumFoundationWasmMemoryByteLength),
                    ],
                ],
            ),
        ].join('\n'),
    );

    sections.push(
        [
            '## Circuit and emitted object census by output width',
            '',
            table(
                [
                    'topCount',
                    'Inputs',
                    'Constants',
                    'Linear',
                    'Conjunctions',
                    'Negations',
                    'Outputs',
                    'Chunks',
                    'Logical payload per participant',
                    'Participant chunk corpus',
                    'Ten-body chunk corpus',
                    'Manifest',
                    'Label entropy per participant',
                    'Maximum live wires',
                ],
                perWidth.map(({ topCount, tally, emitted }) => [
                    String(topCount),
                    formatCount(tally.inputWireCount),
                    formatCount(tally.constantCount),
                    formatCount(tally.linearCount),
                    formatCount(tally.conjunctionCount),
                    formatCount(tally.negationCount),
                    formatCount(tally.outputWires.length),
                    formatCount(emitted.chunkCount),
                    formatCount(emitted.logicalPayloadByteLength),
                    formatCount(emitted.participantChunkCorpusByteLength),
                    formatCount(emitted.completeChunkCorpusByteLength),
                    formatCount(emitted.manifestByteLength),
                    formatCount(emitted.participantLabelEntropyByteLength),
                    formatCount(emitted.maximumLiveWireCount),
                ]),
            ),
        ].join('\n'),
    );

    sections.push(
        [
            '## Scalar command and checkpoint lengths by output width',
            '',
            'Requests carry one participant chunk per evaluation call. Lengths are bytes.',
            '',
            table(
                [
                    'topCount',
                    'Maximum chunk',
                    'Maximum generation checkpoint',
                    'Maximum evaluation checkpoint',
                    'Maximum generation request',
                    'Maximum evaluation request',
                    'Maximum generation response',
                    'Maximum evaluation response',
                ],
                perWidth.map(({ topCount, emitted }) => [
                    String(topCount),
                    formatCount(emitted.maximumChunkByteLength),
                    formatCount(emitted.maximumGenerationCheckpointByteLength),
                    formatCount(emitted.maximumEvaluationCheckpointByteLength),
                    formatCount(
                        emitted.maximumChunkGenerationRequestByteLength,
                    ),
                    formatCount(
                        emitted.maximumChunkEvaluationRequestByteLength,
                    ),
                    formatCount(
                        emitted.maximumChunkGenerationResponseByteLength,
                    ),
                    formatCount(
                        emitted.maximumChunkEvaluationResponseByteLength,
                    ),
                ]),
            ),
        ].join('\n'),
    );

    sections.push(
        [
            '## Clean verified download by output width',
            '',
            'The all-submitted column is the absolute maximum. The quorum-submitted column has eight submissions and two abstentions.',
            '',
            table(
                [
                    'topCount',
                    'Activation inventory',
                    'Preparation recipient bytes',
                    'Parent inventory',
                    'Source inventory (all submitted)',
                    'Clean download (all submitted)',
                    'Clean download (eight submitted)',
                ],
                perWidth.map(
                    ({
                        topCount,
                        resourceAllSubmitted,
                        resourceQuorumSubmitted,
                    }) => [
                        String(topCount),
                        formatCount(
                            resourceAllSubmitted.activationInventoryByteLength,
                        ),
                        formatCount(
                            resourceAllSubmitted.maximumPrivatePreparationRecipientByteLength,
                        ),
                        formatCount(
                            resourceAllSubmitted.preparationParentInventoryByteLength,
                        ),
                        formatCount(
                            resourceAllSubmitted.sourceInventoryByteLength,
                        ),
                        formatCount(
                            resourceAllSubmitted.cleanVerifiedDownloadByteLength,
                        ),
                        formatCount(
                            resourceQuorumSubmitted.cleanVerifiedDownloadByteLength,
                        ),
                    ],
                ),
            ),
        ].join('\n'),
    );

    sections.push(
        [
            '## Operation-key and KMAC census by output width',
            '',
            'Label keys are independently sampled direct labels. Continuation keys count both alternatives for every receiver and conjunction. Selected-evaluation calls are one complete verified inventory.',
            '',
            table(
                [
                    'topCount',
                    'Label keys',
                    'Continuation keys',
                    'Operation keys',
                    'Label outputs',
                    'Continuation outputs',
                    'Generation calls',
                    'Selected-evaluation calls',
                    'Unavailable-label replacements',
                    'Counterfactual replacements',
                    'Maximum label fan-out',
                ],
                perWidth.map(({ topCount, tally }) => {
                    const census = tally.kmacCensus;
                    return [
                        String(topCount),
                        formatCount(census.labelKeyCount),
                        formatCount(census.continuationKeyCount),
                        formatCount(census.keyCount),
                        formatCount(census.labelOutputCount),
                        formatCount(census.continuationOutputCount),
                        formatCount(census.generationCallCount),
                        formatCount(census.selectedEvaluationCallCount),
                        formatCount(census.unavailableLabelReplacementCount),
                        formatCount(
                            census.counterfactualContinuationReplacementCount,
                        ),
                        formatCount(census.maximumLabelFanOut),
                    ];
                }),
            ),
            '',
            '### Maximum-width direct-label fan-out distribution',
            '',
            table(
                ['Outputs per key', 'Key count'],
                maximum.tally.kmacCensus.labelFanOutDistribution.map(
                    ([outputs, keys]) => [
                        formatCount(outputs),
                        formatCount(keys),
                    ],
                ),
            ),
        ].join('\n'),
    );

    const preparation = maximum.preparation.preparation;
    sections.push(
        [
            '## Preparation census',
            '',
            table(
                ['Quantity', 'Value'],
                [
                    [
                        'Size-seven subsets',
                        formatCount(preparation.lowSubsetCount),
                    ],
                    [
                        'Size-eight subsets',
                        formatCount(preparation.terminalSubsetCount),
                    ],
                    [
                        'Aggregate subset keys',
                        formatCount(preparation.aggregateSubsetKeyCount),
                    ],
                    [
                        'Committed contributions',
                        formatCount(preparation.contributionCount),
                    ],
                    [
                        'Remote opening occurrences',
                        formatCount(preparation.remoteOpeningOccurrenceCount),
                    ],
                    [
                        'Directed pairwise masters',
                        formatCount(preparation.directedPairwiseMasterCount),
                    ],
                    [
                        'Held subset keys per participant',
                        formatCount(
                            preparation.heldSubsetKeyCountPerParticipant,
                        ),
                    ],
                    [
                        'Preparation plaintext bytes',
                        formatCount(preparation.preparationPlaintextByteLength),
                    ],
                    [
                        'Hidden honest source bits against a corrupt triple',
                        formatCount(
                            corruptProjection.hiddenHonestSourceBitCount,
                        ),
                    ],
                    [
                        'Extractable corrupt source bits against a corrupt triple',
                        formatCount(
                            corruptProjection.extractableCorruptSourceBitCount,
                        ),
                    ],
                ],
            ),
            '',
            '### Derived-stream census by output width',
            '',
            table(
                [
                    'topCount',
                    'Generation chunks',
                    'Distinct derived subkeys',
                    'Scalar subkey derivations',
                    'Distinct AES blocks',
                    'Scalar AES encryptions',
                ],
                perWidth.map(({ topCount, preparation: model }) => [
                    String(topCount),
                    formatCount(model.streams.generationChunkCount),
                    formatCount(model.streams.uniqueDerivedSubkeyCount),
                    formatCount(
                        model.streams.maximumDerivedSubkeyInvocationCount,
                    ),
                    formatCount(model.streams.distinctAesBlockCount),
                    formatCount(model.streams.scalarAesInvocationCount),
                ]),
            ),
            '',
            '### Maximum-width derived-stream families',
            '',
            table(
                [
                    'Family',
                    'Distinct subkeys',
                    'Distinct AES blocks',
                    'Scalar AES encryptions',
                ],
                [
                    [
                        'Matched low mask',
                        formatCount(
                            maximum.preparation.streams
                                .uniqueMatchedLowSubkeyCount,
                        ),
                        formatCount(
                            maximum.preparation.streams
                                .distinctMatchedLowAesBlockCount,
                        ),
                        formatCount(
                            maximum.preparation.streams
                                .scalarMatchedLowAesInvocationCount,
                        ),
                    ],
                    [
                        'Matched high zero mask',
                        formatCount(
                            maximum.preparation.streams
                                .uniqueMatchedHighZeroSubkeyCount,
                        ),
                        formatCount(
                            maximum.preparation.streams
                                .distinctMatchedHighZeroAesBlockCount,
                        ),
                        formatCount(
                            maximum.preparation.streams
                                .scalarMatchedHighZeroAesInvocationCount,
                        ),
                    ],
                    [
                        'Terminal zero mask',
                        formatCount(
                            maximum.preparation.streams
                                .uniqueTerminalZeroSubkeyCount,
                        ),
                        formatCount(
                            maximum.preparation.streams
                                .distinctTerminalZeroAesBlockCount,
                        ),
                        formatCount(
                            maximum.preparation.streams
                                .scalarTerminalZeroAesInvocationCount,
                        ),
                    ],
                    [
                        'Source correction',
                        formatCount(
                            maximum.preparation.streams.uniqueSourceSubkeyCount,
                        ),
                        formatCount(
                            maximum.preparation.streams
                                .distinctSourceAesBlockCount,
                        ),
                        formatCount(
                            maximum.preparation.streams
                                .scalarSourceAesInvocationCount,
                        ),
                    ],
                    [
                        'Receiver B',
                        formatCount(
                            maximum.preparation.streams
                                .uniqueReceiverBSubkeyCount,
                        ),
                        formatCount(
                            maximum.preparation.streams
                                .distinctReceiverBAesBlockCount,
                        ),
                        formatCount(
                            maximum.preparation.streams
                                .scalarReceiverBAesInvocationCount,
                        ),
                    ],
                    [
                        'Pairwise P',
                        formatCount(
                            maximum.preparation.streams
                                .uniquePairwisePadSubkeyCount,
                        ),
                        formatCount(
                            maximum.preparation.streams
                                .distinctPairwisePadAesBlockCount,
                        ),
                        formatCount(
                            maximum.preparation.streams
                                .scalarPairwisePadAesInvocationCount,
                        ),
                    ],
                ],
            ),
        ].join('\n'),
    );

    const ledger = maximum.ledger;
    sections.push(
        [
            '## Maximum-width honest work vector',
            '',
            'These are emitted work multiplicities for one complete ceremony. They are not an adversarial query allowance.',
            '',
            table(
                [
                    'Phase',
                    'Family',
                    'Key class',
                    'Message bytes',
                    'Output bytes',
                    'Invocations',
                ],
                ledger.honestWork.operationKmacHistogram.map((entry) => [
                    entry.phase,
                    entry.family,
                    entry.keyClass,
                    formatCount(entry.messageByteLength),
                    formatCount(entry.outputByteLength),
                    formatCount(entry.invocationCount),
                ]),
            ),
            '',
            table(
                ['Quantity', 'Value'],
                [
                    [
                        'Generation KMAC input bytes',
                        formatCount(
                            ledger.honestWork
                                .operationGenerationKmacInputByteLength,
                        ),
                    ],
                    [
                        'Generation KMAC output bytes',
                        formatCount(
                            ledger.honestWork
                                .operationGenerationKmacOutputByteLength,
                        ),
                    ],
                    [
                        'Selected-evaluation KMAC input bytes',
                        formatCount(
                            ledger.honestWork
                                .selectedEvaluationKmacInputByteLengthPerCompleteInventory,
                        ),
                    ],
                    [
                        'Selected-evaluation KMAC output bytes',
                        formatCount(
                            ledger.honestWork
                                .selectedEvaluationKmacOutputByteLengthPerCompleteInventory,
                        ),
                    ],
                    [
                        'Mailbox KDF scalar invocations',
                        formatCount(
                            ledger.honestWork.mailboxKdfScalarInvocationCount,
                        ),
                    ],
                    [
                        'Direct label allocation bytes',
                        formatCount(
                            ledger.honestWork.directLabelAllocationByteLength,
                        ),
                    ],
                    [
                        'Local-record associated data bytes',
                        formatCount(
                            ledger.honestWork
                                .localRecordAssociatedDataByteLength,
                        ),
                    ],
                    [
                        'Explicit random byte draws',
                        formatCount(ledger.randomness.explicitByteDrawLength),
                    ],
                    [
                        'Storage-visible local-record seals',
                        formatCount(ledger.localRecord.storageVisibleSealCount),
                    ],
                    [
                        'Retained local records',
                        formatCount(ledger.localRecord.retainedRecordCount),
                    ],
                    [
                        'Mailbox ciphertexts',
                        formatCount(ledger.foundation.mailboxCiphertextCount),
                    ],
                    [
                        'Mailbox plaintext bytes',
                        formatCount(
                            ledger.foundation.mailboxPlaintextByteLength,
                        ),
                    ],
                    [
                        'Honest signatures',
                        formatCount(ledger.foundation.signatureCount),
                    ],
                ],
            ),
        ].join('\n'),
    );

    sections.push(
        [
            '## Maximum-width game census',
            '',
            'Multiplicities that parameterize the named primitive games. Challenge counts depend on the corrupt set; the table below lists them by corrupt participant count.',
            '',
            table(
                ['Quantity', 'Value'],
                [
                    [
                        'ML-DSA-65 roster keys',
                        formatCount(ledger.foundation.signatureKeyCount),
                    ],
                    [
                        'Honest signing purposes per key',
                        formatCount(
                            ledger.foundation.signaturePurposeQueriesPerKey,
                        ),
                    ],
                    [
                        'ML-KEM-768 mailbox keys',
                        formatCount(ledger.foundation.mailboxKemKeyCount),
                    ],
                    [
                        'Authenticated corrupt-sender decapsulations',
                        formatCount(
                            ledger.foundation
                                .maximumAuthenticatedCorruptSenderDecapsulationCount,
                        ),
                    ],
                    [
                        'Mailbox KDF distinct outputs',
                        formatCount(
                            ledger.foundation.mailboxKmacDistinctOutputCount,
                        ),
                    ],
                    [
                        'Mailbox AEAD keys',
                        formatCount(ledger.foundation.mailboxAeadKeyCount),
                    ],
                    [
                        'Mailbox associated-data bytes',
                        formatCount(
                            ledger.foundation.mailboxAssociatedDataByteLength,
                        ),
                    ],
                    [
                        'Sampled direct labels',
                        formatCount(
                            ledger.operation.directRowHiding
                                .sampledIndependentKeyCount,
                        ),
                    ],
                    [
                        'Inaccessible direct labels (all honest)',
                        formatCount(
                            ledger.operation.directRowHiding
                                .maximumInaccessibleLabelCount,
                        ),
                    ],
                    [
                        'Direct labels with a challenge tuple (all honest)',
                        formatCount(
                            ledger.operation.directRowHiding
                                .maximumNonemptyChallengeKeyCount,
                        ),
                    ],
                    [
                        'Direct challenge outputs (all honest)',
                        formatCount(
                            ledger.operation.directRowHiding
                                .maximumChallengeOutputCount,
                        ),
                    ],
                    [
                        'Alternative-key challenges (all honest)',
                        formatCount(
                            ledger.operation.alternativeKeyHiding
                                .maximumConditionallyFreshKeyCountPerSelectedTranscript,
                        ),
                    ],
                    [
                        'Continuation authenticator bytes',
                        formatCount(
                            ledger.operation.knownKeySecondPreimage
                                .authenticatorByteLength,
                        ),
                    ],
                    [
                        'Distinct local-record contexts',
                        formatCount(ledger.localRecord.distinctContextCount),
                    ],
                    [
                        'Inventory commits',
                        formatCount(ledger.localRecord.inventoryCommitCount),
                    ],
                    [
                        'Storage-visible seals',
                        formatCount(ledger.localRecord.storageVisibleSealCount),
                    ],
                    [
                        'Maximum seals under one context',
                        formatCount(
                            ledger.localRecord.maximumSealsPerExactContext,
                        ),
                    ],
                    [
                        'Storage-visible associated-data bytes',
                        formatCount(
                            ledger.localRecord
                                .storageVisibleAssociatedDataByteLength,
                        ),
                    ],
                    [
                        'Implementation encryption calls',
                        formatCount(
                            ledger.localRecord
                                .implementationEncryptionCallCount,
                        ),
                    ],
                ],
            ),
            '',
            '### Challenge census by corrupt participant count',
            '',
            table(
                [
                    'Corrupt',
                    'Honest receivers',
                    'Sampled honest direct labels',
                    'Inaccessible honest direct labels',
                    'Direct challenge keys',
                    'Direct challenge outputs',
                    'Sampled honest continuation keys',
                    'Alternative-key challenges',
                    'Known-key second-preimage targets',
                ],
                ledger.operation.challengeCensusByCorruptParticipantCount.map(
                    (census) => [
                        String(census.corruptParticipantCount),
                        String(census.honestReceiverCount),
                        formatCount(census.sampledHonestDirectLabelKeyCount),
                        formatCount(
                            census.inaccessibleHonestDirectLabelKeyCount,
                        ),
                        formatCount(census.nonemptyDirectChallengeKeyCount),
                        formatCount(census.directKmacTargetOutputCount),
                        formatCount(census.sampledHonestContinuationKeyCount),
                        formatCount(census.alternativeKeyChallengeCount),
                        formatCount(census.knownKeySecondPreimageTargetCount),
                    ],
                ),
            ),
        ].join('\n'),
    );

    sections.push(
        [
            '## Maximum-width exact statistical terms',
            '',
            'Numerators over the stated power-of-two denominators. Security terms bound a distinguishing event; correctness terms leave the action pending.',
            '',
            table(
                ['Event', 'Numerator', 'Denominator bits', 'Consequence'],
                [
                    ...ledger.securityStatisticalTerms.map((term) => [
                        term.event,
                        formatCount(term.numerator),
                        String(term.denominatorBitLength),
                        term.consequence,
                    ]),
                    ...ledger.correctnessFailures.flatMap((term) =>
                        'numerator' in term
                            ? [
                                  [
                                      term.event,
                                      formatCount(term.numerator),
                                      String(term.denominatorBitLength),
                                      term.consequence,
                                  ],
                              ]
                            : [],
                    ),
                ],
            ),
        ].join('\n'),
    );

    sections.push(
        [
            '## Rejected 192-byte projection by output width',
            '',
            'Static reopening formulas for the rejected wide-key projection. They are not emitted objects and authorize nothing.',
            '',
            table(
                [
                    'topCount',
                    'Chunks',
                    'Participant chunk corpus',
                    'Ten-body chunk corpus',
                    'Label entropy per participant',
                    'Maximum evaluation request',
                    'Maximum generation checkpoint',
                    'Maximum evaluation checkpoint',
                ],
                perWidth.map(({ topCount, dormant }) => [
                    String(topCount),
                    formatCount(dormant.chunkCount),
                    formatCount(dormant.participantChunkCorpusByteLength),
                    formatCount(dormant.completeChunkCorpusByteLength),
                    formatCount(dormant.participantLabelEntropyByteLength),
                    formatCount(
                        dormant.maximumChunkEvaluationRequestByteLength,
                    ),
                    formatCount(dormant.maximumGenerationCheckpointByteLength),
                    formatCount(dormant.maximumEvaluationCheckpointByteLength),
                ]),
            ),
        ].join('\n'),
    );

    return `${sections.join('\n\n')}\n`;
};

/**
 * Table alignment is presentation: Prettier pads cells and separator dashes
 * when a table fits the print width. Comparison ignores that padding so a
 * formatted stored copy still matches the rendered content.
 */
const normalizeCensusLine = (line: string): string =>
    line.startsWith('|')
        ? line
              .split('|')
              .map((cell) => cell.trim().replace(/^-{3,}$/u, '---'))
              .join('|')
        : line;

const normalizeCensusText = (text: string): string[] =>
    text.replace(/\r\n/g, '\n').split('\n').map(normalizeCensusLine);

/**
 * Returns the first differing line number, or undefined when the stored
 * census matches the freshly rendered one.
 */
export const findFirstCensusMismatch = (
    stored: string,
    rendered: string,
): number | undefined => {
    const storedLines = normalizeCensusText(stored);
    const renderedLines = normalizeCensusText(rendered);
    const length = Math.max(storedLines.length, renderedLines.length);
    for (let index = 0; index < length; index += 1) {
        if (storedLines[index] !== renderedLines[index]) return index + 1;
    }
    return undefined;
};

const usage =
    'Usage: generate-documentation-census.ts (--output <file> | --check <file> | --print)';

const main = async (): Promise<void> => {
    const argumentsList = process.argv.slice(2);
    const rendered = renderDocumentationCensus();
    if (argumentsList.length === 1 && argumentsList[0] === '--print') {
        process.stdout.write(rendered);
        return;
    }
    if (argumentsList.length !== 2 || argumentsList[1] === undefined) {
        throw new Error(usage);
    }
    const targetPath = path.resolve(argumentsList[1]);
    if (argumentsList[0] === '--output') {
        await writeFile(targetPath, rendered, 'utf8');
        process.stdout.write(
            `Wrote ${String(Buffer.byteLength(rendered))} bytes to ${targetPath}\n`,
        );
        return;
    }
    if (argumentsList[0] === '--check') {
        const stored = await readFile(targetPath, 'utf8');
        const mismatch = findFirstCensusMismatch(stored, rendered);
        if (mismatch !== undefined) {
            throw new Error(
                `The stored census is stale at line ${String(mismatch)}; regenerate it with --output.`,
            );
        }
        process.stdout.write(`The stored census matches the models.\n`);
        return;
    }
    throw new Error(usage);
};

if (import.meta.main) await main();
