import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { compileBoundedIntegerSharingPrivacyCensus } from '#tests/bounded-integer-sharing-privacy-model.js';
import {
    exactRankingModelConstants,
    compilePackedRankingEvaluationGraph,
    verifyExactRankingModel,
} from '#tests/exact-ranking-model.js';
import { compileGenericCommitAndOpenProofResourceCensus } from '#tests/generic-commit-and-open-proof-resource-model.js';
import { compileParticipantVisitDependencyCensus } from '#tests/participant-visit-dependency-model.js';
import { verifyPublicEncryptedSharingModel } from '#tests/public-encrypted-sharing-model.js';
import { compilePublicEncryptedSharingProofResourceCensus } from '#tests/public-encrypted-sharing-proof-resource-model.js';
import { compileSpecializedSetupPiopResourceCensus } from '#tests/specialized-setup-piop-resource-model.js';
import { compileSupportedThresholdCompletionProfiles } from '#tests/threshold-completion-model.js';
import { verifyThresholdKeyAggregationModel } from '#tests/threshold-key-aggregation-model.js';
import { compileThresholdKeyAggregationResourceLowerBound } from '#tests/threshold-key-aggregation-resource-model.js';
import { compileThresholdReleaseNoiseCensus } from '#tests/threshold-release-noise-model.js';

const formatCount = (value: bigint | number): string =>
    `\`${value.toLocaleString('en-US')}\``;

const table = (
    header: readonly string[],
    rows: readonly (readonly string[])[],
): string =>
    [
        `| ${header.join(' | ')} |`,
        `| ${header.map(() => '---').join(' | ')} |`,
        ...rows.map((row) => `| ${row.join(' | ')} |`),
    ].join('\n');

export const renderDocumentationCensus = (): string => {
    const thresholdProfiles = compileSupportedThresholdCompletionProfiles();
    const boundedIntegerSharing = compileBoundedIntegerSharingPrivacyCensus();
    const thresholdKeyAggregation = verifyThresholdKeyAggregationModel();
    const thresholdKeyResources =
        compileThresholdKeyAggregationResourceLowerBound();
    const thresholdReleaseNoise = compileThresholdReleaseNoiseCensus();
    const participantVisits = compileParticipantVisitDependencyCensus();
    const publicEncryptedSharing = verifyPublicEncryptedSharingModel();
    const publicEncryptedSharingProof =
        compilePublicEncryptedSharingProofResourceCensus();
    const specializedSetupPiop = compileSpecializedSetupPiopResourceCensus();
    const genericProofResources =
        compileGenericCommitAndOpenProofResourceCensus();
    if (
        thresholdKeyAggregation.maximumScaledReconstructionCoefficientOneNorm !==
            thresholdReleaseNoise.exactMaximumScaledReconstructionCoefficientOneNorm ||
        thresholdKeyAggregation.maximumSimulationCoefficientOneNorm !==
            thresholdReleaseNoise.exactMaximumSimulationCoefficientOneNorm
    ) {
        throw new Error(
            'Independent modular and rational interpolation models disagree.',
        );
    }
    const rankingCensus = verifyExactRankingModel();
    const completionGraph = compilePackedRankingEvaluationGraph(10, 10, 10);
    const maximumGraph = compilePackedRankingEvaluationGraph(20, 20, 20);

    return `${[
        '# Documentation census',
        '',
        'Generated by `pnpm run docs:census` from the independent TypeScript models under `tests/`. Do not edit by hand. These are model-derived development values, not a protocol theorem, concrete FHE parameter approval, browser measurement, or supported-phone qualification.',
        '',
        '## Threshold completion census',
        '',
        'For each supported roster, the model uses `f = floor((n - 1) / 3)`, all `n` setup receipts, inventory-certificate threshold `q = n - f`, and result-release threshold `d = f + 1`. All-roster receipts leave at least `n - 2f >= d` honest verified share holders after any `f` disappear. A `q` publication or close certificate has at least `n - 2f` honest locked signers, leaving at most `2f < q` positions able to pass it with the conflicting certificate. Every named set is counted; isomorphic joint cases are checked with exact multiplicity, and profiles through twelve participants are also brute-force cross-checked over the underlying bit masks.',
        '',
        table(
            [
                'Participants',
                'Maximum corrupt',
                'Inventory certificate',
                'Result release',
                'Setup receipts',
                'Guaranteed honest responders / publication waiters',
                'Minimum certificate intersection',
                'Maximum post-close publication signers',
                'Mandatory release positions',
                'Corruption/disappearance/refusal cases',
                'Ordered certificate pairs',
                'Brute-force cross-check',
            ],
            thresholdProfiles.map((profile) => [
                String(profile.participantCount),
                String(profile.maximumCorruptParticipantCount),
                String(profile.inventoryCertificateThreshold),
                String(profile.resultReleaseThreshold),
                String(profile.setupReceiptThreshold),
                String(profile.guaranteedHonestResponderCount),
                String(profile.minimumCertificateIntersection),
                String(profile.maximumPostClosePublicationSignerCount),
                String(profile.mandatoryReleaseParticipantCount),
                formatCount(profile.corruptionDisappearanceRefusalCaseCount),
                formatCount(profile.orderedCertificatePairCount),
                profile.bruteForceCrossChecked ? 'yes' : 'class-counted',
            ]),
        ),
        '',
        '## Threshold key-aggregation structural census',
        '',
        'This finite-ring model checks that independently generated linear encryption, relinearization, and rotation-key contributions aggregate under one global secret, while degree-three Shamir redistributions at the KLLPS-style monomial points reconstruct from every four-position subset. It also checks the target-dependent flooded partial-decryption equation for every subset. It omits commitments, proofs, encryption of private shares, rounding correctness, and security reductions.',
        '',
        table(
            ['Property', 'Value'],
            [
                [
                    'Participant count',
                    formatCount(thresholdKeyAggregation.participantCount),
                ],
                [
                    'Release threshold',
                    formatCount(thresholdKeyAggregation.releaseThreshold),
                ],
                [
                    'Authorized release subsets checked',
                    formatCount(
                        thresholdKeyAggregation.authorizedReleaseSetCount,
                    ),
                ],
                [
                    'Monomial interpolation points',
                    formatCount(
                        thresholdKeyAggregation.monomialInterpolationPointCount,
                    ),
                ],
                [
                    'Linear aggregate key equations checked',
                    formatCount(
                        thresholdKeyAggregation.aggregatePublicKeyEquationCount,
                    ),
                ],
                [
                    'Flooded release equations checked',
                    formatCount(thresholdKeyAggregation.releaseEquationCount),
                ],
                [
                    'Tampered share changed reconstruction',
                    thresholdKeyAggregation.tamperedShareChangedReconstruction
                        ? 'yes'
                        : 'no',
                ],
                [
                    'Wrong target changed partial decryption',
                    thresholdKeyAggregation.wrongTargetChangedPartialDecryption
                        ? 'yes'
                        : 'no',
                ],
                [
                    'Experiment coefficient modulus',
                    formatCount(thresholdKeyAggregation.coefficientModulus),
                ],
                [
                    'Experiment ring degree',
                    formatCount(thresholdKeyAggregation.ringDegree),
                ],
                [
                    'Experiment gadget length',
                    formatCount(thresholdKeyAggregation.gadgetLength),
                ],
            ],
        ),
        '',
        '## Public encrypted-sharing structural census',
        '',
        'This independent finite-ring model generates one additive share-encryption key per recipient, encrypts every contributor-recipient evaluation of a degree-three Shamir polynomial, adds ciphertexts by recipient, decrypts each aggregate, and reconstructs the common secret from every four-position subset. Its production bound assumes ternary key and ciphertext witnesses and derives a zero-failure coefficient scale from exact convolution bounds. It does not establish Ring-LWE security, public-key witness uniqueness, proof soundness or zero knowledge, the production ring mapping, or browser feasibility.',
        '',
        table(
            ['Property', 'Value'],
            [
                [
                    'Toy ring degree',
                    formatCount(publicEncryptedSharing.toyRingDegree),
                ],
                [
                    'Contributor-recipient ciphertexts checked',
                    formatCount(
                        publicEncryptedSharing.contributorRecipientCiphertextsChecked,
                    ),
                ],
                [
                    'Aggregate ciphertexts checked',
                    formatCount(
                        publicEncryptedSharing.aggregateCiphertextsChecked,
                    ),
                ],
                [
                    'Authorized reconstruction subsets checked',
                    formatCount(
                        publicEncryptedSharing.authorizedReconstructionSubsetsChecked,
                    ),
                ],
                [
                    'Tampered ciphertext changed aggregate share',
                    publicEncryptedSharing.tamperedCiphertextChangedShare
                        ? 'yes'
                        : 'no',
                ],
                [
                    'Production single-ciphertext noise coefficient bound',
                    formatCount(
                        publicEncryptedSharing.productionSingleCiphertextNoiseCoefficientBound,
                    ),
                ],
                [
                    'Production aggregate noise coefficient bound',
                    formatCount(
                        publicEncryptedSharing.productionAggregateNoiseCoefficientBound,
                    ),
                ],
                [
                    'Production share-encoding scale',
                    formatCount(
                        publicEncryptedSharing.productionShareEncodingScale,
                    ),
                ],
            ],
        ),
        '',
        '## Bounded-integer sharing privacy census',
        '',
        'For every corrupt three-position set, this exact reduced-ring model constructs the integral degree-three basis polynomial that equals one at the secret point and zero at the corrupt evaluation points. It exhausts every extreme secret-difference block, lifts the maximum translation across the production ring and ten hybrid steps, and chooses the smallest power-of-two coefficient bound meeting the stated uniform-cube statistical-distance inequality. It then searches a deterministic Proth sequence for a prime above the centered aggregate-share span and verifies the exact Proth witness and transform congruence. The resulting plaintext and share-encryption moduli are arithmetic bounds, not a complete privacy proof, Ring-LWE parameter approval, or implementation.',
        '',
        table(
            ['Property', 'Value'],
            [
                [
                    'Corrupt subsets checked',
                    formatCount(boundedIntegerSharing.corruptSubsetsChecked),
                ],
                [
                    'Reduced-ring blocks',
                    formatCount(boundedIntegerSharing.reducedRingBlockCount),
                ],
                [
                    'Production interpolation-point exponent stride',
                    formatCount(
                        boundedIntegerSharing.productionInterpolationPointExponentStride,
                    ),
                ],
                [
                    'Maximum nonconstant basis one-norm',
                    formatCount(
                        boundedIntegerSharing.maximumBasisNonconstantOneNorm,
                    ),
                ],
                [
                    'Maximum translation one-norm per reduced block',
                    formatCount(
                        boundedIntegerSharing.maximumBlockTranslationOneNorm,
                    ),
                ],
                [
                    'Maximum production translation per contribution',
                    formatCount(
                        boundedIntegerSharing.maximumProductionTranslationOneNormPerContribution,
                    ),
                ],
                [
                    'Maximum ten-hybrid translation',
                    formatCount(
                        boundedIntegerSharing.maximumHybridTranslationOneNorm,
                    ),
                ],
                [
                    'Statistical privacy bits',
                    formatCount(
                        boundedIntegerSharing.statisticalPrivacyBitLength,
                    ),
                ],
                [
                    'Sharing-coefficient sampling bound',
                    formatCount(boundedIntegerSharing.coefficientSamplingBound),
                ],
                [
                    'Aggregate share coefficient bound',
                    formatCount(
                        boundedIntegerSharing.aggregateShareCoefficientBound,
                    ),
                ],
                [
                    'Share plaintext-span bits',
                    formatCount(
                        boundedIntegerSharing.sharePlaintextSpanBitLength,
                    ),
                ],
                [
                    'Share plaintext prime',
                    formatCount(boundedIntegerSharing.sharePlaintextModulus),
                ],
                [
                    'Share plaintext prime bits',
                    formatCount(
                        boundedIntegerSharing.sharePlaintextModulusBitLength,
                    ),
                ],
                [
                    'Share plaintext prime Proth multiplier',
                    formatCount(
                        boundedIntegerSharing.sharePlaintextPrimeMultiplier,
                    ),
                ],
                [
                    'Share plaintext prime Proth exponent',
                    formatCount(
                        boundedIntegerSharing.sharePlaintextTransformExponent,
                    ),
                ],
                [
                    'Share plaintext prime Proth witness',
                    formatCount(
                        boundedIntegerSharing.sharePlaintextPrimeWitness,
                    ),
                ],
                [
                    'Proth candidates checked',
                    formatCount(
                        boundedIntegerSharing.sharePlaintextPrimeCandidateCount,
                    ),
                ],
                [
                    'Share-encryption modulus bits',
                    formatCount(
                        boundedIntegerSharing.shareEncryptionModulusBitLength,
                    ),
                ],
            ],
        ),
        '',
        '## Threshold key-aggregation resource floor',
        '',
        'This lower bound screens a depth-sized BGV layout at polynomial modulus degree 32,768. It retains four 55-bit primes after the qualification graph, assigns one 34-bit prime to each consumed multiplication level, and accounts separately for two 60-bit auxiliary evaluation-key primes. The rejected private-opening representation commits to each of four sharing coefficients separately with the smallest computationally hiding BDLOP18 layout and sends one evaluation plus its three-element opening to each remote recipient. The replacement public encrypted-sharing floor uses the certified bounded-integer plaintext prime and model-derived 21-bit zero-failure encoding scale, one common-matrix public-key ring element per recipient, and two ciphertext ring elements for every contributor-recipient pair. It assumes only one automorphism key and compact bit-packed transfer elements, and omits every proof, framing byte, scratch allocation, and JavaScript/WebAssembly copy. The tuple is a resource falsifier informed by a native development probe, not a security parameter approval or browser result.',
        '',
        table(
            ['Property', 'Value'],
            [
                [
                    'Candidate ciphertext-modulus bits',
                    formatCount(
                        thresholdKeyResources.candidateCiphertextModulusBitLength,
                    ),
                ],
                [
                    'Candidate auxiliary-modulus bits',
                    formatCount(
                        thresholdKeyResources.auxiliaryModulusBitLength,
                    ),
                ],
                [
                    'Candidate combined-modulus bits',
                    formatCount(
                        thresholdKeyResources.candidateCombinedModulusBitLength,
                    ),
                ],
                [
                    'Ciphertext RNS limbs',
                    formatCount(
                        thresholdKeyResources.ciphertextModulusLimbCount,
                    ),
                ],
                [
                    'Serialized ring element',
                    formatCount(
                        thresholdKeyResources.oneSerializedRingElementByteLength,
                    ),
                ],
                [
                    'Ring elements in one public-key contribution',
                    formatCount(
                        thresholdKeyResources.publicKeyContributionRingElementCount,
                    ),
                ],
                [
                    'One public-key contribution',
                    formatCount(
                        thresholdKeyResources.onePublicKeyContributionByteLength,
                    ),
                ],
                [
                    'Ten public-key contributions',
                    formatCount(
                        thresholdKeyResources.publicKeyContributionCorpusByteLength,
                    ),
                ],
                [
                    'Ring elements in four coefficient commitments per contributor',
                    formatCount(
                        thresholdKeyResources.coefficientCommitmentRingElementCountPerContributor,
                    ),
                ],
                [
                    'Four coefficient commitments per contributor',
                    formatCount(
                        thresholdKeyResources.coefficientCommitmentByteLengthPerContributor,
                    ),
                ],
                [
                    'Ten coefficient commitments',
                    formatCount(
                        thresholdKeyResources.coefficientCommitmentCorpusByteLength,
                    ),
                ],
                [
                    'Ring elements in one remote private carrier',
                    formatCount(
                        thresholdKeyResources.minimumPrivateCarrierRingElementCount,
                    ),
                ],
                [
                    'Remote raw-share payload floor',
                    formatCount(
                        thresholdKeyResources.minimumRemoteSharePayloadByteLength,
                    ),
                ],
                [
                    'Private-opening overhead',
                    formatCount(
                        thresholdKeyResources.privateOpeningOverheadByteLength,
                    ),
                ],
                [
                    'Remote private-sharing payload floor',
                    formatCount(
                        thresholdKeyResources.minimumRemotePrivateSharingPayloadByteLength,
                    ),
                ],
                [
                    'Compact-opening proof budget before the variance ceiling',
                    formatCount(
                        thresholdKeyResources.availableCompactOpeningProofCorpusByteLength,
                    ),
                ],
                [
                    'Compact-opening proof budget per remote carrier',
                    formatCount(
                        thresholdKeyResources.availableCompactOpeningProofPerCarrierByteLength,
                    ),
                ],
                [
                    'Share-encryption aggregate noise coefficient bound',
                    formatCount(
                        thresholdKeyResources.shareEncryptionAggregateNoiseCoefficientBound,
                    ),
                ],
                [
                    'Share-encoding scale',
                    formatCount(thresholdKeyResources.shareEncodingScale),
                ],
                [
                    'Share-encryption modulus bits',
                    formatCount(
                        thresholdKeyResources.shareEncryptionModulusBitLength,
                    ),
                ],
                [
                    'Serialized share-encryption ring element',
                    formatCount(
                        thresholdKeyResources.oneSerializedShareEncryptionRingElementByteLength,
                    ),
                ],
                [
                    'Ten share-encryption public keys',
                    formatCount(
                        thresholdKeyResources.shareEncryptionPublicKeyCorpusByteLength,
                    ),
                ],
                [
                    'Ring elements in one optimistic public encrypted share',
                    formatCount(
                        thresholdKeyResources.minimumPublicEncryptedShareCiphertextRingElementCount,
                    ),
                ],
                [
                    'Public encrypted-share corpus floor',
                    formatCount(
                        thresholdKeyResources.minimumPublicEncryptedShareCorpusByteLength,
                    ),
                ],
                [
                    'Public encrypted-sharing setup floor before proofs',
                    formatCount(
                        thresholdKeyResources.minimumPublicEncryptedSharingSetupCorpusByteLength,
                    ),
                ],
                [
                    'Public encrypted-sharing proof budget before the variance ceiling',
                    formatCount(
                        thresholdKeyResources.availablePublicEncryptedSharingProofBudgetByteLength,
                    ),
                ],
                [
                    'Public encrypted-sharing proof budget per contributor',
                    formatCount(
                        thresholdKeyResources.availablePublicEncryptedSharingProofPerContributorByteLength,
                    ),
                ],
                [
                    'Setup transfer corpus floor',
                    formatCount(
                        thresholdKeyResources.minimumSetupTransferCorpusByteLength,
                    ),
                ],
                [
                    'Setup transfer variance ceiling',
                    formatCount(
                        thresholdKeyResources.setupTransferVarianceCeilingByteLength,
                    ),
                ],
                [
                    'Above setup-transfer variance ceiling',
                    thresholdKeyResources.exceedsSetupTransferVarianceCeiling
                        ? 'yes'
                        : 'no',
                ],
                [
                    'Completion evaluation data live set',
                    formatCount(
                        thresholdKeyResources.completionEvaluationDataLiveByteLength,
                    ),
                ],
                [
                    'Aggregate relinearization key live set',
                    formatCount(
                        thresholdKeyResources.aggregateRelinearizationKeyLiveByteLength,
                    ),
                ],
                [
                    'Evaluation plus relinearization floor',
                    formatCount(
                        thresholdKeyResources.minimumEvaluationLiveByteLengthWithRelinearizationKey,
                    ),
                ],
                [
                    'Ciphertexts plus current streamed evaluation-key floor',
                    formatCount(
                        thresholdKeyResources.scheduledPeakCiphertextAndCurrentEvaluationKeyByteLength,
                    ),
                ],
                [
                    'Streaming headroom before scratch and copies',
                    formatCount(
                        thresholdKeyResources.streamingMemoryHeadroomBeforeScratchByteLength,
                    ),
                ],
                [
                    'One-key-pass-per-operation local reads',
                    formatCount(
                        thresholdKeyResources.oneKeyPassPerOperationReadByteLength,
                    ),
                ],
                [
                    'WebAssembly absolute memory bound',
                    formatCount(
                        thresholdKeyResources.webAssemblyAbsoluteMemoryBoundByteLength,
                    ),
                ],
                [
                    'Fully resident evaluation plus relinearization above the absolute bound',
                    thresholdKeyResources.exceedsWebAssemblyAbsoluteMemoryBound
                        ? 'yes'
                        : 'no',
                ],
                [
                    'One aggregate unit-rotation key',
                    formatCount(
                        thresholdKeyResources.aggregateUnitRotationKeyLiveByteLength,
                    ),
                ],
            ],
        ),
        '',
        '## Public encrypted-sharing proof screen',
        '',
        "This optimistic direct-Ligero screen counts two multiplication constraints for each ternary coefficient, one binary constraint for every bit in the bounded-integer sharing coefficients, and one constraint for each linear ring-coordinate equation. It then searches the discrete power-of-two code dimensions in the exact AHIV22 Section 5.3 communication expression, including Merkle authentication paths. The soundness and random-oracle exponents compensate the CMS19 quadratic and cubic losses for an assumed quantum-query bound plus a component margin, but omit the theorem's asymptotic constant. The screen also omits complete modulus conversion, proof framing and roots, a fixed-hash instantiation, release proofs, and every implementation allocation. Expanded witness and encoded-oracle bytes are proof-field representations, not measured live sets.",
        '',
        table(
            ['Property', 'Value'],
            [
                [
                    'Ternary ring elements per contributor',
                    formatCount(
                        publicEncryptedSharingProof.ternaryRingElementCountPerContributor,
                    ),
                ],
                [
                    'Sharing-coefficient decomposition bits',
                    formatCount(
                        publicEncryptedSharingProof.sharingCoefficientDecompositionBitLength,
                    ),
                ],
                [
                    'Binary-decomposition ring elements per contributor',
                    formatCount(
                        publicEncryptedSharingProof.binaryDecompositionRingElementCountPerContributor,
                    ),
                ],
                [
                    'Bounded ring elements per contributor',
                    formatCount(
                        publicEncryptedSharingProof.boundedRingElementCountPerContributor,
                    ),
                ],
                [
                    'Bounded coefficients per contributor',
                    formatCount(
                        publicEncryptedSharingProof.boundedCoefficientCountPerContributor,
                    ),
                ],
                [
                    'Ternary constraints per contributor',
                    formatCount(
                        publicEncryptedSharingProof.ternaryConstraintCountPerContributor,
                    ),
                ],
                [
                    'Binary-decomposition constraints per contributor',
                    formatCount(
                        publicEncryptedSharingProof.binaryDecompositionConstraintCountPerContributor,
                    ),
                ],
                [
                    'Linear constraints per contributor',
                    formatCount(
                        publicEncryptedSharingProof.linearConstraintCountPerContributor,
                    ),
                ],
                [
                    'Optimistic circuit constraints per contributor',
                    formatCount(
                        publicEncryptedSharingProof.optimisticCircuitConstraintCountPerContributor,
                    ),
                ],
                [
                    'Proof field-element bits',
                    formatCount(
                        publicEncryptedSharingProof.proofFieldElementBitLength,
                    ),
                ],
                [
                    'Interactive soundness bits after query-loss compensation',
                    formatCount(
                        publicEncryptedSharingProof.interactiveSoundnessBitLength,
                    ),
                ],
                [
                    'Random-oracle output bits after query-loss compensation',
                    formatCount(
                        publicEncryptedSharingProof.randomOracleOutputBitLength,
                    ),
                ],
                [
                    'Ligero query count',
                    formatCount(publicEncryptedSharingProof.ligeroQueryCount),
                ],
                [
                    'Ligero repetition count',
                    formatCount(
                        publicEncryptedSharingProof.ligeroRepetitionCount,
                    ),
                ],
                [
                    'Ligero message block length',
                    formatCount(
                        publicEncryptedSharingProof.ligeroMessageBlockLength,
                    ),
                ],
                [
                    'Ligero code dimension',
                    formatCount(
                        publicEncryptedSharingProof.ligeroCodeDimension,
                    ),
                ],
                [
                    'Ligero code length',
                    formatCount(publicEncryptedSharingProof.ligeroCodeLength),
                ],
                [
                    'Ligero witness rows',
                    formatCount(
                        publicEncryptedSharingProof.ligeroWitnessRowCount,
                    ),
                ],
                [
                    'Optimistic Ligero proof per contributor',
                    formatCount(
                        publicEncryptedSharingProof.optimisticLigeroProofByteLengthPerContributor,
                    ),
                ],
                [
                    'Optimistic ten-proof corpus',
                    formatCount(
                        publicEncryptedSharingProof.optimisticTenProofCorpusByteLength,
                    ),
                ],
                [
                    'Proof budget remaining per contributor',
                    formatCount(
                        publicEncryptedSharingProof.proofBudgetRemainingByteLengthPerContributor,
                    ),
                ],
                [
                    'Fits setup proof budget before fixed hash and lifting constant',
                    publicEncryptedSharingProof.fitsSetupProofBudgetBeforeFixedHashAndLiftingConstant
                        ? 'yes'
                        : 'no',
                ],
                [
                    'Expanded bounded witness per contributor',
                    formatCount(
                        publicEncryptedSharingProof.expandedBoundedWitnessByteLengthPerContributor,
                    ),
                ],
                [
                    'Public input per contributor',
                    formatCount(
                        publicEncryptedSharingProof.publicInputByteLengthPerContributor,
                    ),
                ],
                [
                    'Public input plus expanded witness per contributor',
                    formatCount(
                        publicEncryptedSharingProof.publicInputPlusExpandedWitnessByteLengthPerContributor,
                    ),
                ],
                [
                    'Encoded proof-oracle field elements per contributor',
                    formatCount(
                        publicEncryptedSharingProof.encodedProofOracleFieldElementCountPerContributor,
                    ),
                ],
                [
                    'Encoded proof oracle per contributor',
                    formatCount(
                        publicEncryptedSharingProof.encodedProofOracleByteLengthPerContributor,
                    ),
                ],
                [
                    'Encoded proof oracle above setup-storage variance ceiling',
                    publicEncryptedSharingProof.exceedsSetupStorageVarianceCeiling
                        ? 'yes'
                        : 'no',
                ],
            ],
        ),
        '',
        '## Specialized setup PIOP screen',
        '',
        'This optimistic screen extends the HLS25 randomized-encoding, norm-check, linear-check, and row-check formulas to the bounded KLSW, share-encryption, and degree-three sharing witnesses, then charges BCS-style field responses, Merkle paths, and one root per polynomial oracle at the CMS19 query-compensated hash length. It assumes one extra randomized-encoding point and batches the algebra into two linear checks and two row checks. It omits the actual modulus-conversion relation, proof-round transcript, round-by-round-soundness proof, fixed hash, framing, allocator state, computation time, and restart I/O. Passing this screen selects only the next falsifier.',
        '',
        table(
            ['Property', 'Value'],
            [
                [
                    'Randomized-encoding polynomial length',
                    formatCount(
                        specializedSetupPiop.randomizedEncodingPolynomialLength,
                    ),
                ],
                [
                    'Randomized-encoding oracles per contributor',
                    formatCount(
                        specializedSetupPiop.randomizedEncodingOracleCountPerContributor,
                    ),
                ],
                [
                    'Polynomial oracles per contributor',
                    formatCount(
                        specializedSetupPiop.polynomialOracleCountPerContributor,
                    ),
                ],
                [
                    'Query field elements per contributor',
                    formatCount(
                        specializedSetupPiop.queryFieldElementCountPerContributor,
                    ),
                ],
                [
                    'Encoded oracle field elements per contributor',
                    formatCount(
                        specializedSetupPiop.encodedOracleFieldElementCountPerContributor,
                    ),
                ],
                [
                    'Encoded oracle bytes per contributor',
                    formatCount(
                        specializedSetupPiop.encodedOracleByteLengthPerContributor,
                    ),
                ],
                [
                    'Merkle authentication bytes per contributor',
                    formatCount(
                        specializedSetupPiop.merkleAuthenticationByteLengthPerContributor,
                    ),
                ],
                [
                    'Optimistic proof bytes per contributor',
                    formatCount(
                        specializedSetupPiop.optimisticProofByteLengthPerContributor,
                    ),
                ],
                [
                    'Optimistic ten-proof corpus',
                    formatCount(
                        specializedSetupPiop.optimisticTenProofCorpusByteLength,
                    ),
                ],
                [
                    'Public input, expanded witness, oracle, and Merkle bytes per contributor',
                    formatCount(
                        specializedSetupPiop.publicInputWitnessOracleAndMerkleByteLengthPerContributor,
                    ),
                ],
                [
                    'Maximum streaming row bytes',
                    formatCount(
                        specializedSetupPiop.maximumStreamingRowByteLength,
                    ),
                ],
                [
                    'Fits setup transfer variance ceiling',
                    specializedSetupPiop.fitsSetupTransferVarianceCeiling
                        ? 'yes'
                        : 'no',
                ],
                [
                    'Fits setup storage planning target',
                    specializedSetupPiop.fitsSetupStoragePlanningTarget
                        ? 'yes'
                        : 'no',
                ],
            ],
        ),
        '',
        '## Threshold release flooding bound',
        '',
        'For ten participants and release threshold four, one rational-ring implementation enumerates every coefficient over the reduced degree-eight negacyclic subring, while the independent modular-ring model obtains the same maxima. The KLLPS26 trigonometric expression remains as a looser analytic cross-check. All noise-budget figures are floors from the dominant flooding term only: they omit the expanded public-proof radius, remaining correctness terms, proof slack, multi-query and multi-session unions, and hidden constants. They are not approved FHE parameters.',
        '',
        table(
            ['Property', 'Value'],
            [
                [
                    'Authorized release subsets enumerated',
                    formatCount(thresholdReleaseNoise.authorizedSubsetCount),
                ],
                [
                    'Production interpolation-point exponent stride',
                    formatCount(
                        thresholdReleaseNoise.productionInterpolationPointExponentStride,
                    ),
                ],
                [
                    'Bounded-integer scaled reconstructions checked',
                    formatCount(
                        thresholdReleaseNoise.boundedIntegerSharingReconstructionCount,
                    ),
                ],
                [
                    'Lagrange coefficients enumerated',
                    formatCount(thresholdReleaseNoise.lagrangeCoefficientCount),
                ],
                [
                    'Exact maximum scaled reconstruction coefficient one-norm',
                    formatCount(
                        thresholdReleaseNoise.exactMaximumScaledReconstructionCoefficientOneNorm,
                    ),
                ],
                [
                    'Exact maximum simulation coefficient one-norm',
                    formatCount(
                        thresholdReleaseNoise.exactMaximumSimulationCoefficientOneNorm,
                    ),
                ],
                [
                    'Exact interpolation product',
                    formatCount(
                        thresholdReleaseNoise.exactInterpolationProduct,
                    ),
                ],
                [
                    'Trigonometric interpolation-product upper bound',
                    `\`${thresholdReleaseNoise.interpolationProductBound.toFixed(6)}\``,
                ],
                [
                    'Exact dominant noise-budget floor at 80 statistical bits',
                    formatCount(
                        thresholdReleaseNoise.exactTargetSecurityDominantNoiseBudgetLowerBoundBitLength,
                    ),
                ],
                [
                    'Exact dominant noise-budget floor at 128 statistical bits',
                    formatCount(
                        thresholdReleaseNoise.exactConservativeSecurityDominantNoiseBudgetLowerBoundBitLength,
                    ),
                ],
                [
                    'Analytic dominant noise-budget floor at 80 statistical bits',
                    formatCount(
                        thresholdReleaseNoise.targetSecurityDominantNoiseBudgetLowerBoundBitLength,
                    ),
                ],
                [
                    'Analytic dominant noise-budget floor at 128 statistical bits',
                    formatCount(
                        thresholdReleaseNoise.conservativeSecurityDominantNoiseBudgetLowerBoundBitLength,
                    ),
                ],
            ],
        ),
        '',
        '## Generic commit-and-open setup-proof floor',
        '',
        'This optimistic subtotal applies the pinned 128-bit quantum ZKB++/Unruh repetition count and only the binary-multiplication term of its proof-size formula to the bounded coefficients in the depth-sized setup witness. It charges an unrealistically favorable one non-linear gate per bounded coefficient and omits all inputs, commitments, openings, linear work, encrypted sharing expansion, and proof framing. It rejects this direct generic compiler for setup, not commit-and-open proofs or lattice-native proofs as families.',
        '',
        table(
            ['Property', 'Value'],
            [
                [
                    'Quantum-security parallel repetitions',
                    formatCount(
                        genericProofResources.quantumSecurityParallelRepetitionCount,
                    ),
                ],
                [
                    'Proof bits per binary multiplication gate',
                    formatCount(
                        genericProofResources.proofBitsPerBinaryMultiplicationGate,
                    ),
                ],
                [
                    'Bounded ring elements per setup witness',
                    formatCount(
                        genericProofResources.boundedRingElementCountPerSetupContribution,
                    ),
                ],
                [
                    'Bounded coefficients per setup witness',
                    formatCount(
                        genericProofResources.boundedCoefficientCountPerSetupContribution,
                    ),
                ],
                [
                    'Proof floor per setup contribution',
                    formatCount(
                        genericProofResources.minimumProofSizePerSetupContributionByteLength,
                    ),
                ],
                [
                    'Ten-proof corpus floor',
                    formatCount(
                        genericProofResources.minimumProofCorpusByteLength,
                    ),
                ],
                [
                    'Setup plus proof subtotal',
                    formatCount(
                        genericProofResources.combinedSetupAndProofSubtotalByteLength,
                    ),
                ],
                [
                    'Above setup-transfer variance ceiling',
                    genericProofResources.exceedsSetupTransferVarianceCeiling
                        ? 'yes'
                        : 'no',
                ],
            ],
        ),
        '',
        '## Participant visit dependency census',
        '',
        'This dependency lower bound counts the current fixed-roster candidate with separate common-string commitment and opening, one setup-contribution wave, receipt and ballot co-publication, evidence-carrying ballot echo and ready waves, close-log convergence, target certification, release, and retrieval. It assumes each stage fits its foreground-time budget and does not establish browser feasibility.',
        '',
        table(
            ['Property', 'Value'],
            [
                [
                    'Successful-result visits for an early release author',
                    formatCount(participantVisits.successfulResultVisitCount),
                ],
                [
                    'No-result visits for an early target signer',
                    formatCount(participantVisits.noResultVisitCount),
                ],
                [
                    'Preferred visit count',
                    formatCount(participantVisits.preferredVisitCount),
                ],
                [
                    'Mandatory visit ceiling',
                    formatCount(participantVisits.maximumPermittedVisitCount),
                ],
                [
                    'Within preferred count',
                    participantVisits.withinPreferredVisitCount ? 'yes' : 'no',
                ],
                [
                    'Within mandatory ceiling',
                    participantVisits.withinMaximumVisitCount ? 'yes' : 'no',
                ],
            ],
        ),
        '',
        '## Exact ranking arithmetic census',
        '',
        table(
            ['Property', 'Value'],
            [
                [
                    'Plaintext modulus used by the arithmetic experiment',
                    formatCount(exactRankingModelConstants.plaintextModulus),
                ],
                [
                    'Maximum total difference magnitude',
                    formatCount(exactRankingModelConstants.maximumDifference),
                ],
                [
                    'Comparison interpolation points',
                    formatCount(rankingCensus.exhaustiveComparisonPointCount),
                ],
                [
                    'Comparison polynomial degree',
                    formatCount(rankingCensus.comparisonPolynomialDegree),
                ],
                [
                    'Nonzero comparison coefficients',
                    formatCount(
                        rankingCensus.comparisonPolynomialNonzeroCoefficientCount,
                    ),
                ],
                [
                    'Rank-equality domains checked',
                    formatCount(rankingCensus.equalityDomainCount),
                ],
                [
                    'Packed option/result-width layouts checked',
                    formatCount(rankingCensus.packedLayoutCount),
                ],
                [
                    'Participant/option profiles checked',
                    formatCount(
                        rankingCensus.testedParticipantOptionProfileCount,
                    ),
                ],
                [
                    'Adversarial and deterministic score matrices checked',
                    formatCount(rankingCensus.testedMatrixCount),
                ],
                [
                    'Result-width executions checked',
                    formatCount(rankingCensus.testedTopCountExecutionCount),
                ],
            ],
        ),
        '',
        'The comparison returns one when a lower canonical option position has a nonnegative total difference. This incorporates the lower-position tie rule. Rank-equality polynomials are independently interpolated and exhaustively checked on every rank domain from two through twenty options.',
        '',
        '## Packed ranking graph census',
        '',
        'The graph uses one packed ciphertext per accepted ballot. Each power-of-two option block reserves the requested-rank lanes, then carries every opponent-minus-current score difference. Slot-varying coefficients select strict or non-strict comparison according to the canonical tie order, so one block-size-24 Paterson-Stockmeyer evaluation computes every ordered-pair predicate. Repeated unit-direction rotations accumulate one encrypted rank per block and copy it backward across the requested-rank lanes; one slot-varying equality evaluation yields a one-hot encoding of exactly the requested identifiers. The terminal decoder checks and converts that leakage-equivalent encoding. The ciphertext-byte projection assumes a polynomial modulus degree of 32,768, 64-bit RNS limbs, and one remaining data prime per consumed multiplicative level; the release-capable resource screen separately retains its bottom-prime reserve. It counts scheduled data ciphertexts only; evaluation keys, scratch allocations, serialization copies, proof data, and the WebAssembly runtime are additional. This is not a selected parameter set.',
        '',
        table(
            [
                'Graph property',
                'Ten participants/options',
                'Twenty participants/options',
            ],
            [
                [
                    'Ordered pair-difference lanes',
                    formatCount(completionGraph.orderedPairDifferenceLaneCount),
                    formatCount(maximumGraph.orderedPairDifferenceLaneCount),
                ],
                [
                    'Packed ballot lanes including block padding',
                    formatCount(completionGraph.packedBallotLaneCount),
                    formatCount(maximumGraph.packedBallotLaneCount),
                ],
                [
                    'Multiplicative depth',
                    formatCount(completionGraph.multiplicativeDepth),
                    formatCount(maximumGraph.multiplicativeDepth),
                ],
                [
                    'Ciphertext multiplications',
                    formatCount(completionGraph.ciphertextMultiplicationCount),
                    formatCount(maximumGraph.ciphertextMultiplicationCount),
                ],
                [
                    'Relinearizations',
                    formatCount(completionGraph.relinearizationCount),
                    formatCount(maximumGraph.relinearizationCount),
                ],
                [
                    'Relinearization-key ring-limb reads with one pass per operation',
                    formatCount(
                        completionGraph.relinearizationKeyRingLimbReadCount,
                    ),
                    formatCount(
                        maximumGraph.relinearizationKeyRingLimbReadCount,
                    ),
                ],
                [
                    'Rotations',
                    formatCount(completionGraph.rotationCount),
                    formatCount(maximumGraph.rotationCount),
                ],
                [
                    'Rotation-key ring-limb reads with one pass per operation',
                    formatCount(completionGraph.rotationKeyRingLimbReadCount),
                    formatCount(maximumGraph.rotationKeyRingLimbReadCount),
                ],
                [
                    'Ciphertext additions',
                    formatCount(completionGraph.ciphertextAdditionCount),
                    formatCount(maximumGraph.ciphertextAdditionCount),
                ],
                [
                    'Plaintext multiplications',
                    formatCount(completionGraph.plaintextMultiplicationCount),
                    formatCount(maximumGraph.plaintextMultiplicationCount),
                ],
                [
                    'Scheduled peak live ciphertexts',
                    formatCount(
                        completionGraph.scheduledPeakLiveCiphertextCount,
                    ),
                    formatCount(maximumGraph.scheduledPeakLiveCiphertextCount),
                ],
                [
                    'Projected scheduled peak ciphertext bytes',
                    formatCount(
                        completionGraph.scheduledPeakCiphertextByteLength,
                    ),
                    formatCount(maximumGraph.scheduledPeakCiphertextByteLength),
                ],
                [
                    'Materialized graph nodes',
                    formatCount(
                        completionGraph.materializedCiphertextNodeCount,
                    ),
                    formatCount(maximumGraph.materializedCiphertextNodeCount),
                ],
            ],
        ),
    ].join('\n')}\n`;
};

const normalizeCensusLine = (line: string): string =>
    line.startsWith('|')
        ? line
              .split('|')
              .map((cell) => cell.trim().replace(/^-{3,}$/u, '---'))
              .join('|')
        : line;

const normalizeCensusText = (text: string): string[] =>
    text.replace(/\r\n/g, '\n').split('\n').map(normalizeCensusLine);

export const findFirstCensusMismatch = (
    stored: string,
    rendered: string,
): number | undefined => {
    const storedLines = normalizeCensusText(stored);
    const renderedLines = normalizeCensusText(rendered);
    const length = Math.max(storedLines.length, renderedLines.length);
    for (let index = 0; index < length; index += 1) {
        if (storedLines[index] !== renderedLines[index]) return index + 1;
    }
    return undefined;
};

const usage =
    'Usage: generate-documentation-census.ts (--output <file> | --check <file> | --print)';

const main = async (): Promise<void> => {
    const rawArguments = process.argv.slice(2);
    const argumentsList =
        rawArguments[0] === '--' ? rawArguments.slice(1) : rawArguments;
    const rendered = renderDocumentationCensus();
    if (argumentsList.length === 1 && argumentsList[0] === '--print') {
        process.stdout.write(rendered);
        return;
    }
    if (argumentsList.length !== 2 || argumentsList[1] === undefined) {
        throw new Error(usage);
    }
    const targetPath = path.resolve(argumentsList[1]);
    if (argumentsList[0] === '--output') {
        await writeFile(targetPath, rendered, 'utf8');
        process.stdout.write(
            `Wrote ${String(Buffer.byteLength(rendered))} bytes to ${targetPath}\n`,
        );
        return;
    }
    if (argumentsList[0] === '--check') {
        const stored = await readFile(targetPath, 'utf8');
        const mismatch = findFirstCensusMismatch(stored, rendered);
        if (mismatch !== undefined) {
            throw new Error(
                `The stored census is stale at line ${String(mismatch)}; regenerate it with --output.`,
            );
        }
        process.stdout.write('The stored census matches the models.\n');
        return;
    }
    throw new Error(usage);
};

if (import.meta.main) await main();
