[package]
name = "registration-proof"
version = "0.0.0"
edition = "2024"
publish = false
autobins = false


[lib]
crate-type = ["rlib"]

[dependencies]
setup-witness = { path = "../setup-witness" }
setup-stream-kernel = { path = "../setup-stream-kernel" }
supported-profile = { path = "../supported-profile" }
num-bigint = "=0.5.1"
parallel-work = { path = "../parallel-work" }
word-proof = { path = "../word-proof" }
word-verifier = { path = "../word-verifier" }

[dev-dependencies]
word-proof = { path = "../word-proof", features = ["test-support"] }
