/** Internal command identifiers shared by every action-randomness WASM caller. */
export const actionRandomnessCommandIdentifiers = Object.freeze({
    open: 1,
    close: 2,
    setupMailboxEncapsulate: 3,
    ordinaryProofAttempt: 5,
    targetReleaseAttempt: 6,
    freshBallotAttempt: 7,
    createAndSeal: 8,
    openSealed: 9,
    setupActionRandomnessAuthorization: 10,
    validateSetupMailboxSourceKeys: 11,
    setupMailboxSignatureHedge: 12,
    setupObjectSignatureHedge: 16,
    prepareSetupIntentCarrier: 17,
    preparePublicRandomnessCommitmentCarrier: 18,
    preparePublicRandomnessRevealCarrier: 19,
    finishSetupTranscriptCarrier: 20,
    cancelSetupTranscriptCarrier: 21,
    prepareDealerPublicRecordCarrier: 22,
} as const);
