use super::super::*;
use std::{
    collections::BTreeMap,
    sync::{Arc, Mutex, OnceLock},
};

pub(in super::super) const TRUSTEE_EVALUATION_KEY_PROOF_CHECKPOINT_DIRECTORY: &str =
    "trustee-evaluation-key-proof-material";

#[derive(Clone, Eq, Ord, PartialEq, PartialOrd)]
struct CurrentRunProofCacheKey {
    family_directory: String,
    statement_hash_hex: String,
}

type CurrentRunProofBytesCell = Arc<OnceLock<Arc<[u8]>>>;

// CI proves each deterministic statement fresh once. Tests that need the same
// proof in a second independent verifier session reuse only bytes generated and
// semantically verified inside this process; nothing crosses run boundaries.
static CURRENT_RUN_PROOF_BYTES_BY_KEY: OnceLock<
    Mutex<BTreeMap<CurrentRunProofCacheKey, CurrentRunProofBytesCell>>,
> = OnceLock::new();

fn current_run_proof_bytes(
    cache_key: CurrentRunProofCacheKey,
    initialize: impl FnOnce() -> Arc<[u8]>,
) -> Arc<[u8]> {
    let proof_bytes_cell = {
        let mut proof_bytes_by_key = CURRENT_RUN_PROOF_BYTES_BY_KEY
            .get_or_init(|| Mutex::new(BTreeMap::new()))
            .lock()
            .expect("current-run proof byte cache lock");
        Arc::clone(
            proof_bytes_by_key
                .entry(cache_key)
                .or_insert_with(|| Arc::new(OnceLock::new())),
        )
    };

    Arc::clone(proof_bytes_cell.get_or_init(initialize))
}

fn proof_checkpoint_path(family_directory: &str, statement_hash_hex: &str) -> std::path::PathBuf {
    crate::bgv::setup::accepted_setup_final_package_material_store_checkpoint_directory()
        .join(family_directory)
        .join(format!("{statement_hash_hex}.bin"))
}

pub(in super::super) fn persist_checkpointed_proof_bytes(
    family_directory: &str,
    statement_hash_hex: &str,
    proof_bytes: &[u8],
) {
    if !final_package_checkpoint_resume_enabled() {
        return;
    }
    let path = proof_checkpoint_path(family_directory, statement_hash_hex);
    persist_proof_checkpoint(&path, statement_hash_hex, proof_bytes);
}

pub(in super::super) struct CheckpointedProofBytes {
    pub(in super::super) proof_bytes: Vec<u8>,
    pub(in super::super) was_semantically_verified: bool,
}

// The verification state lets callers authenticate and retain a resumed proof
// without repeating the expensive semantic verifier that already gated its
// checkpoint refresh. Freshly generated bytes still require one verifier pass
// before their raw allocation can be replaced by an opaque binding lease.
pub(in super::super) fn checkpointed_proof_bytes_with_verification_state(
    family_directory: &str,
    statement_hash_hex: &str,
    verify_resumed_proof_bytes: impl FnOnce(&[u8]) -> crate::encoding::CanonicalResult<()>,
    generate_proof_bytes: impl FnOnce() -> Vec<u8>,
) -> CheckpointedProofBytes {
    if !final_package_checkpoint_resume_enabled() {
        return CheckpointedProofBytes {
            proof_bytes: generate_proof_bytes(),
            was_semantically_verified: false,
        };
    }
    let path = proof_checkpoint_path(family_directory, statement_hash_hex);
    if let Ok(proof_bytes) = std::fs::read(&path) {
        verify_resumed_proof_bytes(&proof_bytes)
            .expect("resumed proof checkpoint must verify against its current statement");
        refresh_checkpoint_last_used(&path)
            .expect("resumed proof checkpoint modification time must be refreshed");
        final_package_phase(&format!(
            "resumed {family_directory} proof checkpoint {statement_hash_hex}"
        ));
        return CheckpointedProofBytes {
            proof_bytes,
            was_semantically_verified: true,
        };
    }
    let proof_bytes = generate_proof_bytes();
    persist_checkpointed_proof_bytes(family_directory, statement_hash_hex, &proof_bytes);

    CheckpointedProofBytes {
        proof_bytes,
        was_semantically_verified: false,
    }
}

pub(in super::super) fn current_run_checkpointed_proof_bytes(
    family_directory: &str,
    statement_hash_hex: &str,
    verify_proof_bytes: impl Fn(&[u8]) -> crate::encoding::CanonicalResult<()>,
    generate_proof_bytes: impl FnOnce() -> Vec<u8>,
) -> Arc<[u8]> {
    current_run_proof_bytes(
        CurrentRunProofCacheKey {
            family_directory: family_directory.to_string(),
            statement_hash_hex: statement_hash_hex.to_string(),
        },
        || {
            let CheckpointedProofBytes {
                proof_bytes,
                was_semantically_verified,
            } = checkpointed_proof_bytes_with_verification_state(
                family_directory,
                statement_hash_hex,
                |proof_bytes| verify_proof_bytes(proof_bytes),
                generate_proof_bytes,
            );
            if !was_semantically_verified {
                verify_proof_bytes(&proof_bytes)
                    .expect("fresh current-run proof bytes must verify before reuse");
            }
            Arc::from(proof_bytes)
        },
    )
}

fn refresh_checkpoint_last_used(path: &std::path::Path) -> std::io::Result<()> {
    std::fs::OpenOptions::new()
        .write(true)
        .open(path)
        .and_then(|file| {
            file.set_times(std::fs::FileTimes::new().set_modified(std::time::SystemTime::now()))
        })
}

fn persist_proof_checkpoint(path: &std::path::Path, statement_hash_hex: &str, proof_bytes: &[u8]) {
    let Some(parent) = path.parent() else {
        return;
    };
    std::fs::create_dir_all(parent).expect("proof checkpoint directory");
    // Publish atomically through a process-unique temporary file so a concurrent
    // reader never observes a torn write and parallel writers never collide. If a
    // sibling process published the identical content first, the rename fails and
    // the temporary is discarded.
    let temporary_path = parent.join(format!(
        "{statement_hash_hex}.{}.partial",
        std::process::id()
    ));
    std::fs::write(&temporary_path, proof_bytes).expect("proof checkpoint write");
    if std::fs::rename(&temporary_path, path).is_err() {
        let _ = std::fs::remove_file(&temporary_path);
    }
}

pub(in super::super) fn final_package_checkpoint_resume_enabled() -> bool {
    matches!(
        std::env::var("SEALED_LATTICE_RESUME_TEST_CHECKPOINTS").as_deref(),
        Ok("1")
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicUsize, Ordering};

    #[test]
    fn current_run_proof_byte_cache_initializes_once() {
        let initialization_count = AtomicUsize::new(0);
        let cache_key = CurrentRunProofCacheKey {
            family_directory: "current-run-cache-test".to_string(),
            statement_hash_hex: format!("process-{}", std::process::id()),
        };
        let first = current_run_proof_bytes(cache_key.clone(), || {
            initialization_count.fetch_add(1, Ordering::SeqCst);
            Arc::from([3_u8, 1, 4, 1, 5])
        });
        let second = current_run_proof_bytes(cache_key, || {
            panic!("an initialized current-run proof must not run a second producer")
        });

        assert!(Arc::ptr_eq(&first, &second));
        assert_eq!(initialization_count.load(Ordering::SeqCst), 1);
    }
}
