use super::super::*;

// Checkpoint subdirectories for the expensive proof families. The trustee
// evaluation-key family already persists its transported proof material under a
// sibling directory; these two cover the other expensive prover outputs so a
// resumed run skips re-proving every family, not just the trustee one.
pub(in super::super) const SAME_SECRET_BRIDGE_PROOF_CHECKPOINT_DIRECTORY: &str =
    "same-secret-bridge-proof-material";
pub(in super::super) const PUBLIC_KEY_SHARE_PROOF_CHECKPOINT_DIRECTORY: &str =
    "public-key-share-proof-material";
pub(in super::super) const TRUSTEE_EVALUATION_KEY_PROOF_CHECKPOINT_DIRECTORY: &str =
    "trustee-evaluation-key-proof-material";

fn proof_checkpoint_path(family_directory: &str, statement_hash_hex: &str) -> std::path::PathBuf {
    crate::bgv::setup::accepted_setup_final_package_material_store_checkpoint_directory()
        .join(family_directory)
        .join(format!("{statement_hash_hex}.bin"))
}

pub(in super::super) fn persist_checkpointed_proof_bytes(
    family_directory: &str,
    statement_hash_hex: &str,
    proof_bytes: &[u8],
) {
    if !final_package_checkpoint_resume_enabled() {
        return;
    }
    let path = proof_checkpoint_path(family_directory, statement_hash_hex);
    persist_proof_checkpoint(&path, statement_hash_hex, proof_bytes);
}

// Returns deterministic encoded proof bytes,
// loading them from an on-disk checkpoint when checkpoint resume is enabled and a
// matching file exists, and otherwise generating them and persisting them so a
// later run can skip the prover. The statement hash content-addresses the proof:
// a changed statement yields a new filename, so a stale proof is never reused,
// and a witness-only divergence surfaces as a loud verifier rejection rather than
// a silently accepted wrong proof.
pub(in super::super) fn checkpointed_proof_bytes(
    family_directory: &str,
    statement_hash_hex: &str,
    verify_resumed_proof_bytes: impl FnOnce(&[u8]) -> crate::encoding::CanonicalResult<()>,
    generate_proof_bytes: impl FnOnce() -> Vec<u8>,
) -> Vec<u8> {
    checkpointed_proof_bytes_with_verification_state(
        family_directory,
        statement_hash_hex,
        verify_resumed_proof_bytes,
        generate_proof_bytes,
    )
    .proof_bytes
}

pub(in super::super) struct CheckpointedProofBytes {
    pub(in super::super) proof_bytes: Vec<u8>,
    pub(in super::super) was_semantically_verified: bool,
}

// The verification state lets callers authenticate and retain a resumed proof
// without repeating the expensive semantic verifier that already gated its
// checkpoint refresh. Freshly generated bytes still require one verifier pass
// before their raw allocation can be replaced by an opaque binding lease.
pub(in super::super) fn checkpointed_proof_bytes_with_verification_state(
    family_directory: &str,
    statement_hash_hex: &str,
    verify_resumed_proof_bytes: impl FnOnce(&[u8]) -> crate::encoding::CanonicalResult<()>,
    generate_proof_bytes: impl FnOnce() -> Vec<u8>,
) -> CheckpointedProofBytes {
    if !final_package_checkpoint_resume_enabled() {
        return CheckpointedProofBytes {
            proof_bytes: generate_proof_bytes(),
            was_semantically_verified: false,
        };
    }
    let path = proof_checkpoint_path(family_directory, statement_hash_hex);
    if let Ok(proof_bytes) = std::fs::read(&path) {
        verify_resumed_proof_bytes(&proof_bytes)
            .expect("resumed proof checkpoint must verify against its current statement");
        refresh_checkpoint_last_used(&path)
            .expect("resumed proof checkpoint modification time must be refreshed");
        final_package_phase(&format!(
            "resumed {family_directory} proof checkpoint {statement_hash_hex}"
        ));
        return CheckpointedProofBytes {
            proof_bytes,
            was_semantically_verified: true,
        };
    }
    let proof_bytes = generate_proof_bytes();
    persist_checkpointed_proof_bytes(family_directory, statement_hash_hex, &proof_bytes);

    CheckpointedProofBytes {
        proof_bytes,
        was_semantically_verified: false,
    }
}

fn refresh_checkpoint_last_used(path: &std::path::Path) -> std::io::Result<()> {
    std::fs::OpenOptions::new()
        .write(true)
        .open(path)
        .and_then(|file| {
            file.set_times(std::fs::FileTimes::new().set_modified(std::time::SystemTime::now()))
        })
}

fn persist_proof_checkpoint(path: &std::path::Path, statement_hash_hex: &str, proof_bytes: &[u8]) {
    let Some(parent) = path.parent() else {
        return;
    };
    std::fs::create_dir_all(parent).expect("proof checkpoint directory");
    // Publish atomically through a process-unique temporary file so a concurrent
    // reader never observes a torn write and parallel writers never collide. If a
    // sibling process published the identical content first, the rename fails and
    // the temporary is discarded.
    let temporary_path = parent.join(format!(
        "{statement_hash_hex}.{}.partial",
        std::process::id()
    ));
    std::fs::write(&temporary_path, proof_bytes).expect("proof checkpoint write");
    if std::fs::rename(&temporary_path, path).is_err() {
        let _ = std::fs::remove_file(&temporary_path);
    }
}

pub(in super::super) fn final_package_checkpoint_resume_enabled() -> bool {
    matches!(
        std::env::var("SEALED_LATTICE_RESUME_TEST_CHECKPOINTS").as_deref(),
        Ok("1")
    )
}
