name: pages

on:
    push:
        branches:
            - master
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: pages
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
            - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d
            - uses: ./.github/actions/bootstrap-pnpm
            - uses: dtolnay/rust-toolchain@b18f7037bce1ea84c086f4d5e9493f853c0ce412
              with:
                  components: clippy, rustfmt
                  targets: wasm32-unknown-unknown
            - run: pnpm run coverage:badge
            - run: pnpm exec playwright install --with-deps chromium
            - run: pnpm run verify:docs
            - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b
              with:
                  path: ./docs/dist

    deploy:
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - id: deployment
              uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128
